### Payment analysis pharmaceutical industry

* **Goal: Analysis of gender based payment disparity in pharmaceutical industry**
* **Scope General data preprocessing: Clean up, standardization, creating master data file.**

In [1]:
import pandas as pd
import numpy as np
import sys
# ( was required for python setup on OOD cluster)
# ! pip install --upgrade pandas 
# ! pip install --upgrade numpy

In [2]:
# Importing general data
df=pd.read_csv('OP_DTL_GNRL_PGYR2023_P06282024_06122024.csv', low_memory=False)

In [3]:
df_columns=df.columns

In [4]:
l1=list(enumerate(df_columns))
for i,j in l1:
    print(j)

Change_Type
Covered_Recipient_Type
Teaching_Hospital_CCN
Teaching_Hospital_ID
Teaching_Hospital_Name
Covered_Recipient_Profile_ID
Covered_Recipient_NPI
Covered_Recipient_First_Name
Covered_Recipient_Middle_Name
Covered_Recipient_Last_Name
Covered_Recipient_Name_Suffix
Recipient_Primary_Business_Street_Address_Line1
Recipient_Primary_Business_Street_Address_Line2
Recipient_City
Recipient_State
Recipient_Zip_Code
Recipient_Country
Recipient_Province
Recipient_Postal_Code
Covered_Recipient_Primary_Type_1
Covered_Recipient_Primary_Type_2
Covered_Recipient_Primary_Type_3
Covered_Recipient_Primary_Type_4
Covered_Recipient_Primary_Type_5
Covered_Recipient_Primary_Type_6
Covered_Recipient_Specialty_1
Covered_Recipient_Specialty_2
Covered_Recipient_Specialty_3
Covered_Recipient_Specialty_4
Covered_Recipient_Specialty_5
Covered_Recipient_Specialty_6
Covered_Recipient_License_State_code1
Covered_Recipient_License_State_code2
Covered_Recipient_License_State_code3
Covered_Recipient_License_State_code4
Covered_Recipient_License_State_code5
Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
Total_Amount_of_Payment_USDollars
Date_of_Payment
Number_of_Payments_Included_in_Total_Amount
Form_of_Payment_or_Transfer_of_Value
Nature_of_Payment_or_Transfer_of_Value
City_of_Travel
State_of_Travel
Country_of_Travel
Physician_Ownership_Indicator
Third_Party_Payment_Recipient_Indicator
Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value
Charity_Indicator
Third_Party_Equals_Covered_Recipient_Indicator
Contextual_Information
Delay_in_Publication_Indicator
Record_ID
Dispute_Status_for_Publication
Related_Product_Indicator
Covered_or_Noncovered_Indicator_1
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1
Product_Category_or_Therapeutic_Area_1
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1
Associated_Drug_or_Biological_NDC_1
Associated_Device_or_Medical_Supply_PDI_1
Covered_or_Noncovered_Indicator_2
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2
Product_Category_or_Therapeutic_Area_2
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2
Associated_Drug_or_Biological_NDC_2
Associated_Device_or_Medical_Supply_PDI_2
Covered_or_Noncovered_Indicator_3
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3
Product_Category_or_Therapeutic_Area_3
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3
Associated_Drug_or_Biological_NDC_3
Associated_Device_or_Medical_Supply_PDI_3
Covered_or_Noncovered_Indicator_4
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4
Product_Category_or_Therapeutic_Area_4
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4
Associated_Drug_or_Biological_NDC_4
Associated_Device_or_Medical_Supply_PDI_4
Covered_or_Noncovered_Indicator_5
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5
Product_Category_or_Therapeutic_Area_5
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
Associated_Drug_or_Biological_NDC_5
Associated_Device_or_Medical_Supply_PDI_5
Program_Year
Payment_Publication_Date

In [5]:
df.describe()

,Teaching_Hospital_CCN,Teaching_Hospital_ID,Covered_Recipient_Profile_ID,Covered_Recipient_NPI,Covered_Recipient_Specialty_5,Covered_Recipient_Specialty_6,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Total_Amount_of_Payment_USDollars,Number_of_Payments_Included_in_Total_Amount,Record_ID,Program_Year
count,30584.000000,30584.000000,1.457865e+07,1.456601e+07,0.0,0.0,1.460923e+07,1.460923e+07,1.460923e+07,1.460923e+07,14609233.0
mean,251417.184541,13402.775144,4.580372e+06,1.499353e+09,NaN,NaN,1.000001e+11,2.250662e+02,1.016294e+00,1.022339e+09,2023.0
std,148271.825112,417.844783,4.950849e+06,2.879896e+08,NaN,NaN,3.267393e+05,4.122229e+04,5.482408e-01,2.335119e+07,0.0
min,10001.000000,12720.000000,3.000000e+00,1.003000e+09,NaN,NaN,1.000000e+11,1.000000e-02,1.000000e+00,9.658277e+08,2023.0
25%,103304.000000,13061.000000,2.415630e+05,1.245845e+09,NaN,NaN,1.000000e+11,1.470000e+01,1.000000e+00,1.001492e+09,2023.0
50%,240004.000000,13416.000000,1.159879e+06,1.497979e+09,NaN,NaN,1.000000e+11,1.945000e+01,1.000000e+00,1.019992e+09,2023.0
75%,363305.000000,13765.000000,1.071068e+07,1.740891e+09,NaN,NaN,1.000000e+11,2.748000e+01,1.000000e+00,1.048153e+09,2023.0
max,670034.000000,14072.000000,1.156613e+07,1.993000e+09,NaN,NaN,1.000014e+11,8.837730e+07,6.400000e+02,1.060937e+09,2023.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 91 columns):
 #   Column                                                             Dtype
---  ------                                                             -----
 0   Change_Type                                                        object
 1   Covered_Recipient_Type                                             object
 2   Teaching_Hospital_CCN                                              float64
 3   Teaching_Hospital_ID                                               float64
 4   Teaching_Hospital_Name                                             object
 5   Covered_Recipient_Profile_ID                                       float64
 6   Covered_Recipient_NPI                                              float64
 7   Covered_Recipient_First_Name                                       object
 8   Covered_Recipient_Middle_Name                                      object
 9   Covered_Recipient_Last_Name                                        object
 10  Covered_Recipient_Name_Suffix                                      object
 11  Recipient_Primary_Business_Street_Address_Line1                    object
 12  Recipient_Primary_Business_Street_Address_Line2                    object
 13  Recipient_City                                                     object
 14  Recipient_State                                                    object
 15  Recipient_Zip_Code                                                 object
 16  Recipient_Country                                                  object
 17  Recipient_Province                                                 object
 18  Recipient_Postal_Code                                              object
 19  Covered_Recipient_Primary_Type_1                                   object
 20  Covered_Recipient_Primary_Type_2                                   object
 21  Covered_Recipient_Primary_Type_3                                   object
 22  Covered_Recipient_Primary_Type_4                                   object
 23  Covered_Recipient_Primary_Type_5                                   object
 24  Covered_Recipient_Primary_Type_6                                   object
 25  Covered_Recipient_Specialty_1                                      object
 26  Covered_Recipient_Specialty_2                                      object
 27  Covered_Recipient_Specialty_3                                      object
 28  Covered_Recipient_Specialty_4                                      object
 29  Covered_Recipient_Specialty_5                                      float64
 30  Covered_Recipient_Specialty_6                                      float64
 31  Covered_Recipient_License_State_code1                              object
 32  Covered_Recipient_License_State_code2                              object
 33  Covered_Recipient_License_State_code3                              object
 34  Covered_Recipient_License_State_code4                              object
 35  Covered_Recipient_License_State_code5                              object
 36  Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name          object
 37  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID        int64
 38  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name      object
 39  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State     object
 40  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country   object
 41  Total_Amount_of_Payment_USDollars                                  float64
 42  Date_of_Payment                                                    object
 43  Number_of_Payments_Included_in_Total_Amount                        int64
 44  Form_of_Payment_or_Transfer_of_Value                               object
 45  Nature_of_Payment_or_Transfer_of_Value                             object
 46  City_of_Travel                                                     object
 47  State_of_Travel                                                    object
 48  Country_of_Travel                                                  object
 49  Physician_Ownership_Indicator                                      object
 50  Third_Party_Payment_Recipient_Indicator                            object
 51  Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value  object
 52  Charity_Indicator                                                  object
 53  Third_Party_Equals_Covered_Recipient_Indicator                     object
 54  Contextual_Information                                             object
 55  Delay_in_Publication_Indicator                                     object
 56  Record_ID                                                          int64
 57  Dispute_Status_for_Publication                                     object
 58  Related_Product_Indicator                                          object
 59  Covered_or_Noncovered_Indicator_1                                  object
 60  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1          object
 61  Product_Category_or_Therapeutic_Area_1                             object
 62  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1           object
 63  Associated_Drug_or_Biological_NDC_1                                object
 64  Associated_Device_or_Medical_Supply_PDI_1                          object
 65  Covered_or_Noncovered_Indicator_2                                  object
 66  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2          object
 67  Product_Category_or_Therapeutic_Area_2                             object
 68  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2           object
 69  Associated_Drug_or_Biological_NDC_2                                object
 70  Associated_Device_or_Medical_Supply_PDI_2                          object
 71  Covered_or_Noncovered_Indicator_3                                  object
 72  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3          object
 73  Product_Category_or_Therapeutic_Area_3                             object
 74  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3           object
 75  Associated_Drug_or_Biological_NDC_3                                object
 76  Associated_Device_or_Medical_Supply_PDI_3                          object
 77  Covered_or_Noncovered_Indicator_4                                  object
 78  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4          object
 79  Product_Category_or_Therapeutic_Area_4                             object
 80  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4           object
 81  Associated_Drug_or_Biological_NDC_4                                object
 82  Associated_Device_or_Medical_Supply_PDI_4                          object
 83  Covered_or_Noncovered_Indicator_5                                  object
 84  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5          object
 85  Product_Category_or_Therapeutic_Area_5                             object
 86  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5           object
 87  Associated_Drug_or_Biological_NDC_5                                object
 88  Associated_Device_or_Medical_Supply_PDI_5                          object
 89  Program_Year                                                       int64
 90  Payment_Publication_Date                                           object
dtypes: float64(7), int64(4), object(80)
memory usage: 9.9+ GB

In [7]:
df[['Change_Type','Covered_Recipient_Type', 'Covered_Recipient_Profile_ID',
    'Covered_Recipient_NPI', 'Covered_Recipient_First_Name']].describe()

       Covered_Recipient_Profile_ID  Covered_Recipient_NPI
count                  1.457865e+07           1.456601e+07
mean                   4.580372e+06           1.499353e+09
std                    4.950849e+06           2.879896e+08
min                    3.000000e+00           1.003000e+09
25%                    2.415630e+05           1.245845e+09
50%                    1.159879e+06           1.497979e+09
75%                    1.071068e+07           1.740891e+09
max                    1.156613e+07           1.993000e+09

In [8]:
df['Covered_Recipient_NPI']=df['Covered_Recipient_NPI'].astype(object)

In [9]:
df['Covered_Recipient_Profile_ID']=df['Covered_Recipient_Profile_ID'].astype(object)

In [10]:
df[['Change_Type','Covered_Recipient_Type', 'Covered_Recipient_Profile_ID',
    'Covered_Recipient_NPI', 'Covered_Recipient_First_Name']].describe()

##### Analyze names...

,Change_Type,Covered_Recipient_Type,Covered_Recipient_Profile_ID,Covered_Recipient_NPI,Covered_Recipient_First_Name
count,14609233,14609233,14578649.0,1.456601e+07,14578551
unique,1,3,934451.0,9.298370e+05,97294
top,NEW,Covered Recipient Physician,232968.0,1.124221e+09,MICHAEL
freq,14609233,9603554,1159.0,1.159000e+03,242666

In [11]:
df[['Change_Type','Covered_Recipient_Type', 'Covered_Recipient_Profile_ID',
    'Covered_Recipient_NPI', 'Covered_Recipient_First_Name']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 5 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Change_Type                   object
 1   Covered_Recipient_Type        object
 2   Covered_Recipient_Profile_ID  object
 3   Covered_Recipient_NPI         object
 4   Covered_Recipient_First_Name  object
dtypes: object(5)
memory usage: 557.3+ MB

In [12]:
df[['Change_Type']].value_counts(dropna=False)

Change_Type
NEW            14609233
Name: count, dtype: int64

In [13]:
df[['Covered_Recipient_Type']].value_counts(dropna=False)

Covered_Recipient_Type
Covered Recipient Physician                     9603554
Covered Recipient Non-Physician Practitioner    4975095
Covered Recipient Teaching Hospital               30584
Name: count, dtype: int64

In [14]:
df[['Covered_Recipient_Profile_ID']].value_counts(dropna=False)

Covered_Recipient_Profile_ID
NaN                             30584
232968.0                         1159
1299478.0                        1087
154803.0                         1069
649844.0                         1030
                                ...
4215975.0                           1
4215971.0                           1
4215967.0                           1
4215962.0                           1
11566127.0                          1
Name: count, Length: 934452, dtype: int64

In [15]:
df[['Covered_Recipient_NPI']].value_counts(dropna=False)

Covered_Recipient_NPI
NaN                      43219
1.124221e+09              1159
1.669790e+09              1087
1.417030e+09              1069
1.063476e+09              1030
                         ...
1.629664e+09                 1
1.144469e+09                 1
1.629663e+09                 1
1.144469e+09                 1
1.003000e+09                 1
Name: count, Length: 929838, dtype: int64

In [16]:
print("count of unique names", df[['Covered_Recipient_First_Name']].nunique())

count of unique names Covered_Recipient_First_Name    97294
dtype: int64

In [17]:
# Converting to lower case

msk = df['Covered_Recipient_First_Name'].notna()
df.loc[msk, 'Covered_Recipient_First_Name'] = df.loc[msk, 'Covered_Recipient_First_Name'].astype(str)
# Converting all names to lower first to verify.
df.loc[msk, 'Covered_Recipient_First_Name']= df.loc[msk,'Covered_Recipient_First_Name'].apply(lambda x: x.lower())
df['Covered_Recipient_First_Name'].nunique()

76634

In [18]:
### Verfiy again after conversion

df[['Change_Type','Covered_Recipient_Type', 'Covered_Recipient_Profile_ID',
    'Covered_Recipient_NPI', 'Covered_Recipient_First_Name']].describe()

,Change_Type,Covered_Recipient_Type,Covered_Recipient_Profile_ID,Covered_Recipient_NPI,Covered_Recipient_First_Name
count,14609233,14609233,14578649.0,1.456601e+07,14578551
unique,1,3,934451.0,9.298370e+05,76634
top,NEW,Covered Recipient Physician,232968.0,1.124221e+09,michael
freq,14609233,9603554,1159.0,1.159000e+03,251584

In [19]:
9.298370e+05

929837.0

### Teaching hospitals

In [20]:
df[['Teaching_Hospital_CCN']]=df[['Teaching_Hospital_CCN']].astype(object)
df[['Teaching_Hospital_ID']]=df[['Teaching_Hospital_ID']].astype(object)

In [21]:
df[['Teaching_Hospital_CCN','Teaching_Hospital_ID','Teaching_Hospital_Name']].describe()

,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name
count,30584.0,30584.0,30584
unique,1202.0,1202.0,2133
top,390111.0,12957.0,Hospital Of The Univ Of Penna
freq,676.0,676.0,533

In [22]:
df[['Teaching_Hospital_CCN','Teaching_Hospital_ID','Teaching_Hospital_Name']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 3 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Teaching_Hospital_CCN   object
 1   Teaching_Hospital_ID    object
 2   Teaching_Hospital_Name  object
dtypes: object(3)
memory usage: 334.4+ MB

In [23]:
df[['Teaching_Hospital_CCN']].value_counts(dropna=False)

Teaching_Hospital_CCN
NaN                      14578649
390111.0                      676
360180.0                      555
230046.0                      523
330059.0                      469
                           ...
280030.0                        1
450674.0                        1
250082.0                        1
450697.0                        1
50690.0                         1
Name: count, Length: 1203, dtype: int64

In [24]:
df[['Teaching_Hospital_ID']].value_counts(dropna=False)

Teaching_Hospital_ID
NaN                     14578649
12957.0                      676
13096.0                      555
13271.0                      523
12813.0                      469
                          ...
13372.0                        1
13104.0                        1
13918.0                        1
13246.0                        1
13415.0                        1
Name: count, Length: 1203, dtype: int64

In [25]:
df[['Teaching_Hospital_Name']].value_counts(dropna=False)

Teaching_Hospital_Name
NaN                                     14578649
Hospital Of The Univ Of Penna                533
Univ Of Mi Hospitals & Hlth Ctrs             438
Univ Of Missouri Health Care                 389
Cleveland Clinic Hospital                    358
                                          ...
Northern Dutchess Hospital                     1
Garnet Health Medical Center - Catsk           1
GUNDERSEN LUTHERAN MEDICAL CENTER  I           1
Norton Hospitals Inc                           1
Kfh - Panorama City                            1
Name: count, Length: 2134, dtype: int64

In [26]:
# Teaching hospital names should be equal to id converting all to lower case

msk = df['Teaching_Hospital_Name'].notna()
df.loc[msk, 'Teaching_Hospital_Name'] = df.loc[msk, 'Teaching_Hospital_Name'].astype(str)
# Converting all names to lower first to verify.
df.loc[msk, 'Teaching_Hospital_Name']= df.loc[msk,'Teaching_Hospital_Name'].apply(lambda x: x.lower())
df['Teaching_Hospital_Name'].nunique()

1228

In [27]:
# Taking id list to check each ID variations
Hospital_id_list=df.Teaching_Hospital_ID.unique()

# Identifying hospital ID with more than one unique names to standardize them
id_list=[]
for i in Hospital_id_list:
    if df[df['Teaching_Hospital_ID']==i]['Teaching_Hospital_Name'].nunique() > 1:
        id_list.append(i)
print('Hospitals ids with multiple names', id_list)

Hospitals ids with multiple names [13231.0, 13584.0, 12743.0, 12933.0, 13135.0, 13486.0, 13070.0, 13526.0, 13155.0, 13467.0, 12732.0, 13471.0, 13892.0, 13693.0, 12935.0, 13413.0, 13494.0, 13127.0, 13761.0, 13409.0, 13516.0, 13431.0, 13273.0, 13752.0, 13250.0, 13506.0]

In [28]:
# Verifying the differences in names for same Teaching_Hospital_IDs.
for i in id_list:
    print("The hospital id", i)
    print(df[df['Teaching_Hospital_ID']==i]['Teaching_Hospital_Name'].value_counts())

The hospital id 13231.0
Teaching_Hospital_Name
spectrum health  hospitals    24
spectrum health hospitals      7
Name: count, dtype: int64
The hospital id 13584.0
Teaching_Hospital_Name
norton hospitals  inc    9
norton hospitals inc     1
Name: count, dtype: int64
The hospital id 12743.0
Teaching_Hospital_Name
lahey clinic hospital  inc.    69
lahey clinic hospital inc.      8
Name: count, dtype: int64
The hospital id 12933.0
Teaching_Hospital_Name
brockton hospital  inc.    8
brockton hospital inc.     1
Name: count, dtype: int64
The hospital id 13135.0
Teaching_Hospital_Name
community health network  inc.    8
community health network inc.     4
Name: count, dtype: int64
The hospital id 13486.0
Teaching_Hospital_Name
forsyth memorial hospital  inc    24
forsyth memorial hospital inc     19
Name: count, dtype: int64
The hospital id 13070.0
Teaching_Hospital_Name
univer.of cincinnati med center llc     27
univer. of cincinnati med center llc     1
Name: count, dtype: int64
The hospital id 13526.0
Teaching_Hospital_Name
au medical center  inc    10
au medical center inc      4
Name: count, dtype: int64
The hospital id 13155.0
Teaching_Hospital_Name
northshore university healthsystem     181
northshore university health system      1
Name: count, dtype: int64
The hospital id 13467.0
Teaching_Hospital_Name
st. marys medical center inc.     5
st. marys medical center  inc.    3
Name: count, dtype: int64
The hospital id 12732.0
Teaching_Hospital_Name
milford regional medical center  inc    3
milford regional medical center inc     1
Name: count, dtype: int64
The hospital id 13471.0
Teaching_Hospital_Name
charleston area medical center  inc.    5
charleston area medical center inc.     2
Name: count, dtype: int64
The hospital id 13892.0
Teaching_Hospital_Name
carle  bromenn medical center    5
carle bromenn medical center     3
Name: count, dtype: int64
The hospital id 13693.0
Teaching_Hospital_Name
baptist health medical center - lr    12
baptist health medical center-lr       1
Name: count, dtype: int64
The hospital id 12935.0
Teaching_Hospital_Name
concord hospital  inc.    7
concord hospital inc.     1
Name: count, dtype: int64
The hospital id 13413.0
Teaching_Hospital_Name
sinai hospital of baltimore  inc.    18
sinai hospital of baltimore inc.     11
Name: count, dtype: int64
The hospital id 13494.0
Teaching_Hospital_Name
phd#1  dba skagit valley hospital    25
phd#1 dba skagit valley hospital      3
Name: count, dtype: int64
The hospital id 13127.0
Teaching_Hospital_Name
methodist hospitals inc     7
methodist hospitals  inc    5
Name: count, dtype: int64
The hospital id 13761.0
Teaching_Hospital_Name
community hospital of indiana  inc.    3
community hospital of indiana inc.     1
Name: count, dtype: int64
The hospital id 13409.0
Teaching_Hospital_Name
st. francis hospital  wilmington    1
st. francis hospital wilmington     1
Name: count, dtype: int64
The hospital id 13516.0
Teaching_Hospital_Name
university health services  inc.    9
university health services inc.     1
Name: count, dtype: int64
The hospital id 13431.0
Teaching_Hospital_Name
prince georges hospital center inc     2
prince georges hospital center  inc    1
Name: count, dtype: int64
The hospital id 13273.0
Teaching_Hospital_Name
aurora health care metro  inc.    9
aurora health care metro inc.     2
Name: count, dtype: int64
The hospital id 13752.0
Teaching_Hospital_Name
knapp medical  center    4
knapp medical center     1
Name: count, dtype: int64
The hospital id 13250.0
Teaching_Hospital_Name
lakeland medical center  st. joseph    18
lakeland medical center st. joseph      2
Name: count, dtype: int64
The hospital id 13506.0
Teaching_Hospital_Name
st marys health care system  inc    2
st marys health care system inc     1
Name: count, dtype: int64

In [29]:
# Making all names same, replacing with the value used maximum time.
for i in  id_list:
    abcd=df[df['Teaching_Hospital_ID']==i]['Teaching_Hospital_Name'].value_counts()
    indexes=df.loc[df['Teaching_Hospital_ID']==i].index
    val=abcd.index[abcd.argmax()]
    df.loc[indexes,'Teaching_Hospital_Name']= val

In [30]:
# Verification
df[['Teaching_Hospital_Name', 'Teaching_Hospital_ID','Teaching_Hospital_CCN']].describe()

,Teaching_Hospital_Name,Teaching_Hospital_ID,Teaching_Hospital_CCN
count,30584,30584.0,30584.0
unique,1202,1202.0,1202.0
top,hospital of the univ of penna,12957.0,390111.0
freq,676,676.0,676.0

In [31]:
# Verification
df[['Teaching_Hospital_Name', 'Teaching_Hospital_ID','Teaching_Hospital_CCN']].value_counts(dropna=False)

Teaching_Hospital_Name            Teaching_Hospital_ID  Teaching_Hospital_CCN
NaN                               NaN                   NaN                      14578649
hospital of the univ of penna     12957.0               390111.0                      676
cleveland clinic hospital         13096.0               360180.0                      555
univ of mi hospitals & hlth ctrs  13271.0               230046.0                      523
montefiore medical center         12813.0               330059.0                      469
                                                                                   ...
laredo medical center             12886.0               450029.0                        1
largo medical center              13603.0               100248.0                        1
saint francis memorial hospital   13993.0               50152.0                         1
city hospital inc.                13469.0               510008.0                        1
forbes regional hospital          13002.0               390267.0                        1
Name: count, Length: 1203, dtype: int64

### Covered recipients

In [32]:
df[['Covered_Recipient_Middle_Name','Covered_Recipient_Last_Name',
   'Covered_Recipient_Name_Suffix','Recipient_Primary_Business_Street_Address_Line1',
   'Recipient_Primary_Business_Street_Address_Line2','Recipient_City',
   'Recipient_State','Recipient_Zip_Code','Recipient_Country','Recipient_Province',
   'Recipient_Postal_Code']].describe()

,Covered_Recipient_Middle_Name,Covered_Recipient_Last_Name,Covered_Recipient_Name_Suffix,Recipient_Primary_Business_Street_Address_Line1,Recipient_Primary_Business_Street_Address_Line2,Recipient_City,Recipient_State,Recipient_Zip_Code,Recipient_Country,Recipient_Province,Recipient_Postal_Code
count,5630345,14578302,141910,14609186,3045299,14609232,14608622,14608622,14609233,554,611
unique,67514,288733,123,735593,76635,22523,59,268550,32,81,166
top,M,PATEL,JR.,9500 EUCLID AVE,SUITE 200,HOUSTON,TX,77030,United States,ONTARIO,20817
freq,334125,97780,34781,12163,90418,181401,1393687,41114,14608622,96,33

In [33]:
df[['Covered_Recipient_Middle_Name','Covered_Recipient_Last_Name',
   'Covered_Recipient_Name_Suffix','Recipient_Primary_Business_Street_Address_Line1',
   'Recipient_Primary_Business_Street_Address_Line2','Recipient_City',
   'Recipient_State','Recipient_Zip_Code','Recipient_Country','Recipient_Province',
   'Recipient_Postal_Code']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 11 columns):
 #   Column                                           Dtype
---  ------                                           -----
 0   Covered_Recipient_Middle_Name                    object
 1   Covered_Recipient_Last_Name                      object
 2   Covered_Recipient_Name_Suffix                    object
 3   Recipient_Primary_Business_Street_Address_Line1  object
 4   Recipient_Primary_Business_Street_Address_Line2  object
 5   Recipient_City                                   object
 6   Recipient_State                                  object
 7   Recipient_Zip_Code                               object
 8   Recipient_Country                                object
 9   Recipient_Province                               object
 10  Recipient_Postal_Code                            object
dtypes: object(11)
memory usage: 1.2+ GB

In [34]:
# Converting to lower case

msk = df['Covered_Recipient_Middle_Name'].notna()
df.loc[msk, 'Covered_Recipient_Middle_Name'] = df.loc[msk, 'Covered_Recipient_Middle_Name'].astype(str)
# Converting all names to lower first to verify.
df.loc[msk, 'Covered_Recipient_Middle_Name']= df.loc[msk,'Covered_Recipient_Middle_Name'].apply(lambda x: x.lower())
df['Covered_Recipient_Middle_Name'].nunique()

52551

In [35]:
df[['Covered_Recipient_Middle_Name']].value_counts(dropna=False)

Covered_Recipient_Middle_Name
NaN                              8978888
m                                 334129
a                                 320258
l                                 260197
j                                 203916
                                  ...
lipumano                               1
lipsky                                 1
lipperini                              1
liorah                                 1
labron                                 1
Name: count, Length: 52552, dtype: int64

In [36]:
# Converting all to lower case

msk = df['Covered_Recipient_Last_Name'].notna()
df.loc[msk, 'Covered_Recipient_Last_Name'] = df.loc[msk, 'Covered_Recipient_Last_Name'].astype(str)
# Converting all names to lower first to verify.
df.loc[msk, 'Covered_Recipient_Last_Name']= df.loc[msk,'Covered_Recipient_Last_Name'].apply(lambda x: x.lower())
df['Covered_Recipient_Last_Name'].nunique()

231718

In [37]:
df[['Covered_Recipient_Last_Name']].value_counts(dropna=False)

Covered_Recipient_Last_Name
patel                          101330
smith                           73203
lee                             54602
johnson                         51973
nguyen                          46549
                                ...
shapelow                            1
gollbach                            1
gollehon                            1
mespelt                             1
\garcia                             1
Name: count, Length: 231719, dtype: int64

In [38]:
df[['Covered_Recipient_Last_Name']].isnull().sum()

Covered_Recipient_Last_Name    30931
dtype: int64

In [39]:
# Converting all to lower case

msk = df['Covered_Recipient_Name_Suffix'].notna()
df.loc[msk, 'Covered_Recipient_Name_Suffix'] = df.loc[msk, 'Covered_Recipient_Name_Suffix'].astype(str)
# Converting all names to lower first to verify.
df.loc[msk, 'Covered_Recipient_Name_Suffix']= df.loc[msk,'Covered_Recipient_Name_Suffix'].apply(lambda x: x.lower())
df['Covered_Recipient_Name_Suffix'].nunique()

103

In [40]:
df[['Covered_Recipient_Name_Suffix']].value_counts(dropna=False)

Covered_Recipient_Name_Suffix
NaN                              14467323
jr.                                 35091
jr                                  30499
iii                                 24665
ii                                  13983
                                   ...
ii od                                   1
(lena                                   1
lpn                                     1
m.b.                                    1
jr od                                   1
Name: count, Length: 104, dtype: int64

In [41]:
df[['Recipient_Primary_Business_Street_Address_Line1']].value_counts(dropna=False)

Recipient_Primary_Business_Street_Address_Line1
9500 EUCLID AVE                                    12163
200 1ST ST SW                                       9010
1515 HOLCOMBE BLVD                                  8868
2500 N STATE ST                                     8630
11100 EUCLID AVE                                    7736
                                                   ...
124 Sw 1st St                                          1
407 CARUSO AVE                                         1
124 Sw Adams St                                        1
124 Sycamore Dr                                        1
"""300 Longwood Avenue, Fegan 4"""                     1
Name: count, Length: 735594, dtype: int64

In [42]:
df[['Recipient_Primary_Business_Street_Address_Line2']].value_counts(dropna=False)

Recipient_Primary_Business_Street_Address_Line2
NaN                                                11563934
SUITE 200                                             90418
SUITE 100                                             78064
STE 200                                               51460
STE 100                                               50425
                                                     ...
ORTHOPAEDIC SURGERY ML 2017                               1
425 W 3RD AVE STE 550                                     1
ORTHOPAEDIC SURG SERVICE MCHK-DSO                         1
ORTHOPAEDIC SPECIALISTS UPMC                              1
MAIN APARTMENT                                            1
Name: count, Length: 76636, dtype: int64

In [43]:
df[['Recipient_City']].value_counts(dropna=False)

Recipient_City
HOUSTON                  181401
NEW YORK                 166865
SAN ANTONIO              104326
DALLAS                   102735
CHICAGO                   96076
                          ...
Mount Laurel Township         1
Mount Joy                     1
Mount Jewett                  1
Mount Hope                    1
NaN                           1
Name: count, Length: 22524, dtype: int64

In [44]:
# Converting all to lower case

msk = df['Recipient_City'].notna()
df.loc[msk, 'Recipient_City'] = df.loc[msk, 'Recipient_City'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Recipient_City']= df.loc[msk,'Recipient_City'].apply(lambda x: x.lower())
df['Recipient_City'].nunique()

13841

In [45]:
df[['Recipient_City']].value_counts(dropna=False) ### check again

Recipient_City
houston               205693
new york              194669
dallas                120284
san antonio           118425
chicago               110261
                       ...
mt laurel township         1
mt pleasant sc             1
mt. clemens                1
mt. washington             1
NaN                        1
Name: count, Length: 13842, dtype: int64

In [46]:
df[['Recipient_State']].value_counts(dropna=False)

Recipient_State
TX                 1393687
FL                 1288517
CA                 1274333
NY                  970410
PA                  638591
OH                  579859
GA                  556461
NC                  519112
IL                  494403
TN                  474723
NJ                  471868
MI                  447997
VA                  359953
AZ                  345524
IN                  339061
MO                  322453
AL                  321913
LA                  314907
KY                  307196
SC                  300297
MD                  284374
MA                  198130
CO                  195015
OK                  194857
CT                  191234
MS                  176548
AR                  155140
KS                  137499
NV                  135485
WA                  131147
UT                  119572
NE                   96137
WV                   95093
WI                   92468
IA                   79864
OR                   70571
MN                   58260
ID                   56480
PR                   53152
HI                   48659
DE                   47086
RI                   44866
NM                   42537
DC                   40477
NH                   29274
SD                   27101
ME                   19460
MT                   18489
ND                   17213
AK                   17133
WY                   10089
VT                    2502
NaN                    611
AE                     511
GU                     373
AP                     356
VI                     187
MP                      16
AS                       1
AA                       1
Name: count, dtype: int64

In [47]:
df[['Recipient_Zip_Code']].value_counts(dropna=False)

Recipient_Zip_Code
77030                 41114
78229                 20711
35801                 15865
14221                 15073
37203                 14144
                      ...
28078-2207                1
37950-2450                1
37950-0998                1
37939-1167                1
02210-1964                1
Name: count, Length: 268551, dtype: int64

In [48]:
df[['Recipient_Country']].value_counts(dropna=False)

Recipient_Country
United States                           14608622
United States Minor Outlying Islands         186
Canada                                       177
Germany                                       51
Japan                                         39
Great Britain (Uk)                            37
Italy                                         24
United Arab Emirates                          17
Singapore                                     13
Pakistan                                      11
Argentina                                      7
Austria                                        6
Korea (Republic of)                            5
Israel                                         5
Saudi Arabia                                   4
Turkey                                         4
Lebanon                                        3
Gabon                                          3
Mexico                                         2
Cook Islands                                   2
China                                          2
Australia                                      2
India                                          2
Uruguay                                        1
Venezuela                                      1
Afghanistan                                    1
Uganda                                         1
Spain                                          1
Qatar                                          1
Hong Kong                                      1
Cameroon                                       1
Wallis And Futuna                              1
Name: count, dtype: int64

In [49]:
df[['Recipient_Province']].value_counts(dropna=False)

Recipient_Province
NaN                   14608679
ONTARIO                     96
MD                          36
LONDON                      25
RHEINLAND-PFALZ             25
                        ...
JEONNAM                      1
OKINAWA                      1
New York                     1
MACCA                        1
MIRANDA                      1
Name: count, Length: 82, dtype: int64

In [50]:
df[['Recipient_Postal_Code']].value_counts(dropna=False)

Recipient_Postal_Code
NaN                      14608622
20817                          33
66849                          32
W1G 7LA                        25
V6K2E-9                        21
                           ...
97239                           1
966-13                          1
96538                           1
110236                          1
33805                           1
Name: count, Length: 167, dtype: int64

In [51]:
# Verifying again after lower case conversion
df[['Covered_Recipient_Middle_Name','Covered_Recipient_Last_Name',
   'Covered_Recipient_Name_Suffix','Recipient_Primary_Business_Street_Address_Line1',
   'Recipient_Primary_Business_Street_Address_Line2','Recipient_City',
   'Recipient_State','Recipient_Zip_Code','Recipient_Country','Recipient_Province',
   'Recipient_Postal_Code']].describe()

,Covered_Recipient_Middle_Name,Covered_Recipient_Last_Name,Covered_Recipient_Name_Suffix,Recipient_Primary_Business_Street_Address_Line1,Recipient_Primary_Business_Street_Address_Line2,Recipient_City,Recipient_State,Recipient_Zip_Code,Recipient_Country,Recipient_Province,Recipient_Postal_Code
count,5630345,14578302,141910,14609186,3045299,14609232,14608622,14608622,14609233,554,611
unique,52551,231718,103,735593,76635,13841,59,268550,32,81,166
top,m,patel,jr.,9500 EUCLID AVE,SUITE 200,houston,TX,77030,United States,ONTARIO,20817
freq,334129,101330,35091,12163,90418,205693,1393687,41114,14608622,96,33

### Covered recipient types

In [52]:
df[['Covered_Recipient_Primary_Type_1', 'Covered_Recipient_Primary_Type_2',
   'Covered_Recipient_Primary_Type_3', 'Covered_Recipient_Primary_Type_4',
   'Covered_Recipient_Primary_Type_5','Covered_Recipient_Primary_Type_6']].describe()

,Covered_Recipient_Primary_Type_1,Covered_Recipient_Primary_Type_2,Covered_Recipient_Primary_Type_3,Covered_Recipient_Primary_Type_4,Covered_Recipient_Primary_Type_5,Covered_Recipient_Primary_Type_6
count,14578649,1261,670,666,666,666
unique,12,5,2,1,1,1
top,Medical Doctor,Nurse Practitioner,Clinical Nurse Specialist,Certified Registered Nurse Anesthetist,Certified Nurse-Midwife,Anesthesiologist Assistant
freq,7915394,723,666,666,666,666

In [53]:
df[['Covered_Recipient_Primary_Type_1', 'Covered_Recipient_Primary_Type_2',
   'Covered_Recipient_Primary_Type_3', 'Covered_Recipient_Primary_Type_4',
   'Covered_Recipient_Primary_Type_5','Covered_Recipient_Primary_Type_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 6 columns):
 #   Column                            Dtype
---  ------                            -----
 0   Covered_Recipient_Primary_Type_1  object
 1   Covered_Recipient_Primary_Type_2  object
 2   Covered_Recipient_Primary_Type_3  object
 3   Covered_Recipient_Primary_Type_4  object
 4   Covered_Recipient_Primary_Type_5  object
 5   Covered_Recipient_Primary_Type_6  object
dtypes: object(6)
memory usage: 668.8+ MB

In [54]:
df['Covered_Recipient_Primary_Type_1'].value_counts(dropna=False)

Covered_Recipient_Primary_Type_1
Medical Doctor                            7915394
Nurse Practitioner                        3266216
Physician Assistant                       1618674
Doctor of Osteopathy                       941772
Doctor of Dentistry                        350087
Doctor of Optometry                        243643
Doctor of Podiatric Medicine               148788
Certified Registered Nurse Anesthetist      47183
NaN                                         30584
Clinical Nurse Specialist                   27678
Certified Nurse-Midwife                     14393
Chiropractor                                 3870
Anesthesiologist Assistant                    951
Name: count, dtype: int64

In [55]:
df['Covered_Recipient_Primary_Type_2'].value_counts(dropna=False)

Covered_Recipient_Primary_Type_2
NaN                                       14607972
Nurse Practitioner                             723
Clinical Nurse Specialist                      276
Certified Nurse-Midwife                        140
Certified Registered Nurse Anesthetist         119
Anesthesiologist Assistant                       3
Name: count, dtype: int64

In [56]:
df['Covered_Recipient_Primary_Type_3'].value_counts(dropna=False)

Covered_Recipient_Primary_Type_3
NaN                                       14608563
Clinical Nurse Specialist                      666
Certified Registered Nurse Anesthetist           4
Name: count, dtype: int64

In [57]:
df[['Covered_Recipient_Primary_Type_4']].value_counts(dropna=False)

Covered_Recipient_Primary_Type_4
NaN                                       14608567
Certified Registered Nurse Anesthetist         666
Name: count, dtype: int64

In [58]:
df[['Covered_Recipient_Primary_Type_5']].value_counts(dropna=False)

Covered_Recipient_Primary_Type_5
NaN                                 14608567
Certified Nurse-Midwife                  666
Name: count, dtype: int64

In [59]:
df[['Covered_Recipient_Primary_Type_6']].value_counts(dropna=False)

Covered_Recipient_Primary_Type_6
NaN                                 14608567
Anesthesiologist Assistant               666
Name: count, dtype: int64

### Covered recipient speciality type

In [60]:
df[['Covered_Recipient_Specialty_1','Covered_Recipient_Specialty_2',
   'Covered_Recipient_Specialty_3','Covered_Recipient_Specialty_4',
   'Covered_Recipient_Specialty_5','Covered_Recipient_Specialty_6']].describe()

       Covered_Recipient_Specialty_5  Covered_Recipient_Specialty_6
count                            0.0                            0.0
mean                             NaN                            NaN
std                              NaN                            NaN
min                              NaN                            NaN
25%                              NaN                            NaN
50%                              NaN                            NaN
75%                              NaN                            NaN
max                              NaN                            NaN

In [61]:
df[['Covered_Recipient_Specialty_1','Covered_Recipient_Specialty_2',
   'Covered_Recipient_Specialty_3','Covered_Recipient_Specialty_4']].describe()

,Covered_Recipient_Specialty_1,Covered_Recipient_Specialty_2,Covered_Recipient_Specialty_3,Covered_Recipient_Specialty_4
count,14578649,5,1,1
unique,385,5,1,1
top,Allopathic & Osteopathic Physicians|Internal M...,Physician Assistants & Advanced Practice Nursi...,Physician Assistants & Advanced Practice Nursi...,Physician Assistants & Advanced Practice Nursi...
freq,1308113,1,1,1

In [62]:
df[['Covered_Recipient_Specialty_1','Covered_Recipient_Specialty_2',
   'Covered_Recipient_Specialty_3','Covered_Recipient_Specialty_4',
   'Covered_Recipient_Specialty_5','Covered_Recipient_Specialty_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 6 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Covered_Recipient_Specialty_1  object
 1   Covered_Recipient_Specialty_2  object
 2   Covered_Recipient_Specialty_3  object
 3   Covered_Recipient_Specialty_4  object
 4   Covered_Recipient_Specialty_5  float64
 5   Covered_Recipient_Specialty_6  float64
dtypes: float64(2), object(4)
memory usage: 668.8+ MB

In [63]:
# Converting all to lower case

msk = df['Covered_Recipient_Specialty_1'].notna()
df.loc[msk, 'Covered_Recipient_Specialty_1'] = df.loc[msk, 'Covered_Recipient_Specialty_1'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Covered_Recipient_Specialty_1']= df.loc[msk,'Covered_Recipient_Specialty_1'].apply(lambda x: x.lower())
df['Covered_Recipient_Specialty_1'].nunique()

385

In [64]:
df[['Covered_Recipient_Specialty_1']].value_counts(dropna=False)

Covered_Recipient_Specialty_1
allopathic & osteopathic physicians|internal medicine                                                  1308113
physician assistants & advanced practice nursing providers|nurse practitioner|family                   1293783
physician assistants & advanced practice nursing providers|physician assistant                         1243486
physician assistants & advanced practice nursing providers|nurse practitioner                          1121875
allopathic & osteopathic physicians|family medicine                                                    1095160
                                                                                                        ...
allopathic & osteopathic physicians|medical genetics|medical biochemical genetics                            1
physician assistants & advanced practice nursing providers|clinical nurse specialist|long-term care          1
allopathic & osteopathic physicians|pediatrics|child abuse pediatrics                                        1
dental providers|dental assistant                                                                            1
eye and vision services providers|technician/technologist|contact lens fitter                                1
Name: count, Length: 386, dtype: int64

In [65]:
df[['Covered_Recipient_Specialty_2']].value_counts(dropna=False)

Covered_Recipient_Specialty_2
NaN                                                                                         14609228
Physician Assistants & Advanced Practice Nursing Providers|Advanced Practice Midwife               1
Physician Assistants & Advanced Practice Nursing Providers|Nurse Practitioner|Acute Care           1
Physician Assistants & Advanced Practice Nursing Providers|Nurse Practitioner|Family               1
Physician Assistants & Advanced Practice Nursing Providers|Nurse Practitioner|Pediatrics           1
Physician Assistants & Advanced Practice Nursing Providers|Physician Assistant|Medical             1
Name: count, dtype: int64

In [66]:
df[['Covered_Recipient_Specialty_3']].value_counts(dropna=False)

Covered_Recipient_Specialty_3
NaN                                                                                           14609232
Physician Assistants & Advanced Practice Nursing Providers|Nurse Practitioner|Primary Care           1
Name: count, dtype: int64

In [67]:
df[['Covered_Recipient_Specialty_4']].value_counts(dropna=False)

Covered_Recipient_Specialty_4
NaN                                                                                                  14609232
Physician Assistants & Advanced Practice Nursing Providers|Nurse Practitioner|Occupational Health           1
Name: count, dtype: int64

In [68]:
df[['Covered_Recipient_Specialty_5']].value_counts(dropna=False)

Covered_Recipient_Specialty_5
NaN                              14609233
Name: count, dtype: int64

In [69]:
df[['Covered_Recipient_Specialty_6']].value_counts(dropna=False)

Covered_Recipient_Specialty_6
NaN                              14609233
Name: count, dtype: int64

In [70]:
# Verifying after converting to lower case
df[['Covered_Recipient_Specialty_1','Covered_Recipient_Specialty_2',
   'Covered_Recipient_Specialty_3','Covered_Recipient_Specialty_4']].describe()

,Covered_Recipient_Specialty_1,Covered_Recipient_Specialty_2,Covered_Recipient_Specialty_3,Covered_Recipient_Specialty_4
count,14578649,5,1,1
unique,385,5,1,1
top,allopathic & osteopathic physicians|internal m...,Physician Assistants & Advanced Practice Nursi...,Physician Assistants & Advanced Practice Nursi...,Physician Assistants & Advanced Practice Nursi...
freq,1308113,1,1,1

### Covered recipient license state codes

In [71]:
df[['Covered_Recipient_License_State_code1','Covered_Recipient_License_State_code2',
   'Covered_Recipient_License_State_code3','Covered_Recipient_License_State_code4',
   'Covered_Recipient_License_State_code5']].describe()

,Covered_Recipient_License_State_code1,Covered_Recipient_License_State_code2,Covered_Recipient_License_State_code3,Covered_Recipient_License_State_code4,Covered_Recipient_License_State_code5
count,14578649,141460,36319,9556,1927
unique,59,55,53,49,43
top,CA,TX,TX,TX,TX
freq,1414511,14371,4193,980,220

In [72]:
df[['Covered_Recipient_License_State_code1','Covered_Recipient_License_State_code2',
   'Covered_Recipient_License_State_code3','Covered_Recipient_License_State_code4',
   'Covered_Recipient_License_State_code5']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 5 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   Covered_Recipient_License_State_code1  object
 1   Covered_Recipient_License_State_code2  object
 2   Covered_Recipient_License_State_code3  object
 3   Covered_Recipient_License_State_code4  object
 4   Covered_Recipient_License_State_code5  object
dtypes: object(5)
memory usage: 557.3+ MB

In [73]:
df[['Covered_Recipient_License_State_code1']].value_counts(dropna=False)

Covered_Recipient_License_State_code1
CA                                       1414511
FL                                       1353291
TX                                       1192647
NY                                        895201
GA                                        572028
PA                                        566147
IL                                        564911
OH                                        544062
NC                                        519614
NJ                                        509466
MI                                        464203
AZ                                        414186
TN                                        387357
AL                                        378651
IN                                        372501
LA                                        328081
KY                                        303939
VA                                        300044
MD                                        279957
MO                                        267977
SC                                        252079
CO                                        227528
MA                                        224562
CT                                        219067
AR                                        193631
OK                                        183833
MS                                        181827
KS                                        170387
IA                                        121683
NV                                        111960
UT                                         98164
WA                                         91358
NE                                         81828
DC                                         75712
WV                                         70608
WI                                         68008
DE                                         66881
MN                                         65107
ID                                         64204
OR                                         62002
HI                                         51659
PR                                         51535
NM                                         47435
RI                                         35813
NaN                                        30584
AK                                         24456
ME                                         22866
NH                                         22693
MT                                         18949
SD                                         18693
ND                                         16096
WY                                          6739
VT                                          1183
GU                                           890
FM                                           237
VI                                           100
MH                                            46
MP                                            34
PW                                            21
AS                                             1
Name: count, dtype: int64

In [74]:
df[['Covered_Recipient_License_State_code2']].value_counts(dropna=False)

Covered_Recipient_License_State_code2
NaN                                      14467773
TX                                          14371
PA                                          10279
NY                                           9931
OH                                           7254
VA                                           6073
MO                                           5761
NC                                           5018
TN                                           4909
MD                                           4636
FL                                           4519
IL                                           4514
MI                                           4411
SC                                           3811
WA                                           3784
NJ                                           3763
GA                                           3624
IN                                           3189
MA                                           3045
KY                                           2916
CA                                           2818
WI                                           2797
OR                                           2333
MN                                           2127
MS                                           1966
LA                                           1891
NV                                           1856
OK                                           1754
UT                                           1653
CO                                           1579
WV                                           1567
NE                                           1469
NM                                           1324
KS                                           1224
NH                                           1005
RI                                            935
IA                                            935
SD                                            837
MT                                            627
HI                                            589
ND                                            555
PR                                            554
ID                                            496
ME                                            471
WY                                            453
DC                                            341
AZ                                            333
VT                                            329
CT                                            313
DE                                            247
AR                                            195
VI                                             36
GU                                             31
AL                                              6
PW                                              3
MP                                              3
Name: count, dtype: int64

In [75]:
df[['Covered_Recipient_License_State_code3']].value_counts(dropna=False)

Covered_Recipient_License_State_code3
NaN                                      14572914
TX                                           4193
PA                                           3978
OH                                           2174
VA                                           2135
NY                                           2005
TN                                           1891
WI                                           1589
WA                                           1413
MO                                           1234
SC                                           1048
NC                                            988
FL                                            919
UT                                            835
MI                                            831
MD                                            810
OR                                            738
NJ                                            702
NV                                            569
IN                                            565
GA                                            533
LA                                            514
WV                                            485
MA                                            480
MN                                            468
OK                                            466
NE                                            463
NM                                            433
MS                                            411
KY                                            405
IL                                            362
RI                                            317
SD                                            267
WY                                            252
ME                                            250
MT                                            242
NH                                            240
ND                                            169
CO                                            156
IA                                            134
CA                                            116
PR                                            100
KS                                            100
VT                                             86
HI                                             74
ID                                             64
GU                                             49
CT                                             16
DE                                             13
VI                                             12
DC                                             12
PW                                              8
AZ                                              3
MP                                              2
Name: count, dtype: int64

In [76]:
df[['Covered_Recipient_License_State_code4']].value_counts(dropna=False)

Covered_Recipient_License_State_code4
NaN                                      14599677
TX                                            980
PA                                            950
VA                                            878
KS                                            602
WI                                            578
NY                                            523
TN                                            479
OH                                            450
WA                                            431
NC                                            386
SC                                            287
MO                                            264
WV                                            175
WY                                            156
NM                                            137
UT                                            135
NJ                                            135
MI                                            133
IA                                            124
NH                                            117
NV                                            114
OK                                            113
NE                                            111
OR                                            105
RI                                            100
IL                                             85
CO                                             82
MN                                             79
KY                                             79
FL                                             78
MA                                             78
SD                                             74
MT                                             61
MS                                             60
ND                                             57
IN                                             55
LA                                             54
VT                                             54
MD                                             42
GA                                             41
ID                                             35
ME                                             25
VI                                             24
CT                                             16
PR                                              8
DE                                              3
HI                                              1
DC                                              1
CA                                              1
Name: count, dtype: int64

In [77]:
df[['Covered_Recipient_License_State_code5']].value_counts(dropna=False)

Covered_Recipient_License_State_code5
NaN                                      14607306
TX                                            220
TN                                            171
VA                                            144
WI                                            136
OH                                            123
WV                                            108
RI                                             99
PA                                             90
WA                                             84
NY                                             68
MO                                             59
SC                                             50
SD                                             40
ND                                             38
NC                                             37
UT                                             34
MS                                             30
WY                                             30
GA                                             29
KY                                             29
OR                                             29
NJ                                             26
NV                                             24
MI                                             23
NM                                             22
NH                                             22
OK                                             22
MD                                             21
ME                                             19
KS                                             18
LA                                             14
CT                                             14
NE                                             11
ID                                              9
VT                                              7
MN                                              6
IL                                              6
MT                                              4
MA                                              3
IN                                              3
DC                                              2
VI                                              2
HI                                              1
Name: count, dtype: int64

### Manufacturer columns

In [78]:
df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID']=df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID'].astype(object)

In [79]:
df[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country',
   ]].describe()

,Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
count,14609233,14609233,14609233,14489802,14609233
unique,1712,1700,1723,47,33
top,ABBVIE INC.,100000000204,ABBVIE INC.,NJ,United States
freq,1762887,1763819,1265485,2900194,14489802

In [80]:
df[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country',
   ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 5 columns):
 #   Column                                                            Dtype
---  ------                                                            -----
 0   Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name         object
 1   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID       object
 2   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name     object
 3   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State    object
 4   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country  object
dtypes: object(5)
memory usage: 557.3+ MB

In [81]:
## Converting all to lower case

msk = df['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].notna()
df.loc[msk, 'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'] = df.loc[msk, 'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name']= df.loc[msk,'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].apply(lambda x: x.lower())
df['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].nunique()

1614

In [82]:
df[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name']].value_counts(dropna=False)

Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name
abbvie inc.                                                  1763819
pfizer inc.                                                   553795
eli lilly and company                                         513489
astrazeneca pharmaceuticals lp                                504748
janssen pharmaceuticals, inc                                  502347
                                                              ...
substrate hd                                                       1
apyx medical corporation                                           1
celtic biodevices llc                                              1
surgebright inc.                                                   1
topcon healthcare solutions, inc.                                  1
Name: count, Length: 1614, dtype: int64

In [83]:
df[['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID']].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID
100000000204                                                   1763819
100000000286                                                    513465
100000000066                                                    506330
100000000144                                                    485058
100000000146                                                    463816
                                                                ...
100000051297                                                         1
100000061304                                                         1
100000000243                                                         1
100000216793                                                         1
100001181912                                                         1
Name: count, Length: 1700, dtype: int64

In [84]:
df[['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name
ABBVIE INC.                                                      1265485
PFIZER INC.                                                       513465
Lilly USA, LLC                                                    506330
AbbVie Inc.                                                       498334
Novo Nordisk Inc                                                  485058
                                                                  ...
CIT Ortho LLC                                                          1
Transcend                                                              1
OraBio, Inc.                                                           1
CELTIC BIODEVICES LLC                                                  1
EarliTec Diagnostics Inc.                                              1
Name: count, Length: 1723, dtype: int64

In [85]:
df[['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']].nunique()

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name    1723
dtype: int64

In [86]:
## Converting all to lower case

msk = df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].notna()
df.loc[msk, 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'] = df.loc[msk, 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']= df.loc[msk,'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].apply(lambda x: x.lower())
df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].nunique()

1698

In [87]:
df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name
abbvie inc.                       1763819
pfizer inc.                        513465
lilly usa, llc                     506330
novo nordisk inc                   485058
astrazeneca pharmaceuticals lp     463816
                                   ...
hand biomechanics laboratory            1
caire inc.                              1
ferring arzneimittel gmbh               1
ferring holding inc.                    1
elekta ab (publ)                        1
Name: count, Length: 1698, dtype: int64

In [88]:
df[['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State']].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State
NJ                                                                2900194
IL                                                                2386466
CA                                                                1693081
MA                                                                1528592
PA                                                                1147907
NY                                                                1041699
IN                                                                 586412
DE                                                                 563918
MN                                                                 483976
MD                                                                 260633
TX                                                                 223719
CT                                                                 220908
FL                                                                 198048
NC                                                                 181859
MI                                                                 167593
GA                                                                 137609
NaN                                                                119431
WI                                                                 108647
TN                                                                  93990
AZ                                                                  84680
CO                                                                  77584
WA                                                                  61133
OH                                                                  51282
MO                                                                  42728
AL                                                                  40818
VA                                                                  39743
UT                                                                  35963
WV                                                                  28645
OR                                                                  27320
DC                                                                  18321
RI                                                                  13289
NV                                                                   9514
SC                                                                   7335
NH                                                                   6733
KY                                                                   4789
PR                                                                   4726
KS                                                                   3907
OK                                                                   3168
IA                                                                    999
SD                                                                    503
MS                                                                    415
LA                                                                    341
MT                                                                    278
ND                                                                    187
AR                                                                    105
NE                                                                     33
NM                                                                     10
ME                                                                      2
Name: count, dtype: int64

In [89]:
df[['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country']].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
United States                                                       14489802
Ireland                                                                74151
Great Britain (Uk)                                                      9471
Iceland                                                                 9233
Bermuda                                                                 8498
Canada                                                                  5335
Switzerland                                                             4382
Germany                                                                 3087
Denmark                                                                 1404
Japan                                                                   1266
Israel                                                                   833
Belgium                                                                  525
France                                                                   510
Sweden                                                                   207
Italy                                                                    111
Austria                                                                   86
Brazil                                                                    79
New Zealand                                                               57
Cayman Islands                                                            53
Korea (Republic of)                                                       46
Australia                                                                 22
Spain                                                                     16
Chile                                                                     15
Netherlands                                                               12
Hong Kong                                                                 12
Singapore                                                                  5
Mexico                                                                     4
South Africa                                                               3
China                                                                      3
Finland                                                                    2
Costa Rica                                                                 1
Colombia                                                                   1
United Arab Emirates                                                       1
Name: count, dtype: int64

In [90]:
## After conversion to lower case

df[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State',
   'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country',
   ]].describe()

,Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
count,14609233,14609233,14609233,14489802,14609233
unique,1614,1700,1698,47,33
top,abbvie inc.,100000000204,abbvie inc.,NJ,United States
freq,1763819,1763819,1763819,2900194,14489802

In [91]:
# Taking id list to check each ID variations
df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID']=df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID'].astype(object)
manuf_gpo_id_list=df.Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID.unique()                                                                     

# Identifying ID with more than one unique names to standardize them
id_list=[]
for i in manuf_gpo_id_list:
    if df[df['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID']==i]['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].nunique() > 1:
        id_list.append(i)
print('Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name', id_list)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name []

In [92]:
df[['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
       'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']].nunique()

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID      1700
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name    1698
dtype: int64

## Manufacture ID can be dropped.

### Payment columns

In [93]:
df[['Total_Amount_of_Payment_USDollars','Date_of_Payment','Number_of_Payments_Included_in_Total_Amount',
    'Form_of_Payment_or_Transfer_of_Value','Nature_of_Payment_or_Transfer_of_Value']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 5 columns):
 #   Column                                       Dtype
---  ------                                       -----
 0   Total_Amount_of_Payment_USDollars            float64
 1   Date_of_Payment                              object
 2   Number_of_Payments_Included_in_Total_Amount  int64
 3   Form_of_Payment_or_Transfer_of_Value         object
 4   Nature_of_Payment_or_Transfer_of_Value       object
dtypes: float64(1), int64(1), object(3)
memory usage: 557.3+ MB

In [94]:
df[['Total_Amount_of_Payment_USDollars','Date_of_Payment',
    'Number_of_Payments_Included_in_Total_Amount',
    'Form_of_Payment_or_Transfer_of_Value',
    'Nature_of_Payment_or_Transfer_of_Value']].describe(include=object)

,Date_of_Payment,Form_of_Payment_or_Transfer_of_Value,Nature_of_Payment_or_Transfer_of_Value
count,14609233,14609233,14609233
unique,365,6,16
top,11/15/2023,In-kind items and services,Food and Beverage
freq,81174,12573826,13380946

In [95]:
# Int and float types
df[['Total_Amount_of_Payment_USDollars',
    'Number_of_Payments_Included_in_Total_Amount']].describe()

,Total_Amount_of_Payment_USDollars,Number_of_Payments_Included_in_Total_Amount
count,1.460923e+07,1.460923e+07
mean,2.250662e+02,1.016294e+00
std,4.122229e+04,5.482408e-01
min,1.000000e-02,1.000000e+00
25%,1.470000e+01,1.000000e+00
50%,1.945000e+01,1.000000e+00
75%,2.748000e+01,1.000000e+00
max,8.837730e+07,6.400000e+02

In [96]:
df[['Total_Amount_of_Payment_USDollars']].value_counts(dropna=False)

Total_Amount_of_Payment_USDollars
125.00                               45375
25.00                                34753
10.00                                29371
20.00                                23765
15.00                                20010
                                     ...
1124.55                                  1
1124.61                                  1
1124.71                                  1
1124.81                                  1
88377304.59                              1
Name: count, Length: 123641, dtype: int64

In [97]:
df[['Date_of_Payment']].value_counts(dropna=False)

Date_of_Payment
11/15/2023         81174
10/25/2023         79764
11/09/2023         77702
10/18/2023         77636
11/16/2023         76878
                   ...
12/30/2023          1135
05/28/2023           997
07/02/2023           771
11/25/2023           655
09/03/2023           576
Name: count, Length: 365, dtype: int64

In [98]:
df[['Number_of_Payments_Included_in_Total_Amount']].value_counts(dropna=False)

Number_of_Payments_Included_in_Total_Amount
1                                              14567561
2                                                 11496
3                                                  5608
4                                                  4024
6                                                  3978
                                                 ...
68                                                    1
66                                                    1
65                                                    1
60                                                    1
640                                                   1
Name: count, Length: 89, dtype: int64

In [99]:
df[['Form_of_Payment_or_Transfer_of_Value']].value_counts(dropna=False)

Form_of_Payment_or_Transfer_of_Value
In-kind items and services                        12573826
Cash or cash equivalent                            2034989
Stock option                                           198
Stock                                                  131
Any other ownership interest                            50
Dividend, profit or other return on investment          39
Name: count, dtype: int64

In [100]:
df[['Nature_of_Payment_or_Transfer_of_Value']].value_counts(dropna=False)

Nature_of_Payment_or_Transfer_of_Value
Food and Beverage                                                                                                                                     13380946
Travel and Lodging                                                                                                                                      543987
Compensation for services other than consulting, including serving as faculty or as a speaker at a venue other than a continuing education program      236305
Consulting Fee                                                                                                                                          171464
Education                                                                                                                                               161097
Gift                                                                                                                                                     31785
Honoraria                                                                                                                                                20242
Royalty or License                                                                                                                                       15880
Compensation for serving as faculty or as a speaker for a medical education program                                                                      12238
Entertainment                                                                                                                                             7967
Space rental or facility fees (teaching hospital only)                                                                                                    7356
Long term medical supply or device loan                                                                                                                   7353
Grant                                                                                                                                                     6170
Debt forgiveness                                                                                                                                          5274
Acquisitions                                                                                                                                               619
Charitable Contribution                                                                                                                                    550
Name: count, dtype: int64

In [101]:
df[['Total_Amount_of_Payment_USDollars']].isnull().sum()

Total_Amount_of_Payment_USDollars    0
dtype: int64

In [102]:
df[['Number_of_Payments_Included_in_Total_Amount']].isnull().sum()

Number_of_Payments_Included_in_Total_Amount    0
dtype: int64

### Travel related

In [103]:
df[['City_of_Travel','State_of_Travel','Country_of_Travel']].describe()

       City_of_Travel State_of_Travel Country_of_Travel
count          543986          529710            543987
unique           9773              56                97
top           Chicago              TX     United States
freq            13989           68142            529710

In [104]:
df[['City_of_Travel','State_of_Travel','Country_of_Travel']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 3 columns):
 #   Column             Dtype
---  ------             -----
 0   City_of_Travel     object
 1   State_of_Travel    object
 2   Country_of_Travel  object
dtypes: object(3)
memory usage: 334.4+ MB

In [105]:
# City of travel to lower case

msk = df['City_of_Travel'].notna()
df.loc[msk, 'City_of_Travel'] = df.loc[msk, 'City_of_Travel'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'City_of_Travel']= df.loc[msk,'City_of_Travel'].apply(lambda x: x.lower())
df['City_of_Travel'].nunique()

6596

In [106]:
df[['City_of_Travel']].value_counts(dropna=False)

City_of_Travel
NaN               14065247
dallas               20680
chicago              20089
atlanta              16284
austin               13148
                    ...
mccoll                   1
mcintosh                 1
mckee                    1
mckenzie                 1
los alamos               1
Name: count, Length: 6597, dtype: int64

In [107]:
df['City_of_Travel'].value_counts(dropna=False)

City_of_Travel
NaN                 14065247
dallas                 20680
chicago                20089
atlanta                16284
austin                 13148
                      ...
plattsburg                 1
keystone heights           1
augustine                  1
west memphis               1
huxley                     1
Name: count, Length: 6597, dtype: int64

In [108]:
df[['State_of_Travel']].value_counts(dropna=False)

State_of_Travel
NaN                14079523
TX                    68142
CA                    62741
FL                    61212
IL                    31470
GA                    22975
TN                    19417
MN                    18927
NY                    18818
PA                    18222
NJ                    17673
CO                    17271
AZ                    16336
MA                    15336
NC                    14314
NV                    11284
OH                     9772
VA                     8127
LA                     7637
MI                     7335
WA                     7093
MO                     6031
DC                     5471
IN                     5367
MD                     5080
UT                     5038
SC                     4799
OK                     3956
KS                     3915
KY                     3637
OR                     3238
AL                     3087
CT                     2987
WI                     2900
HI                     2095
AR                     1825
IA                     1690
NE                     1674
MS                     1554
ID                     1514
PR                     1382
NM                     1217
WV                     1136
RI                      847
MT                      834
AK                      753
NH                      701
DE                      692
ME                      624
SD                      603
ND                      506
WY                      309
VT                      125
VI                        8
AS                        6
PW                        4
GU                        3
Name: count, dtype: int64

In [109]:
# Converting all to lower case

msk = df['Country_of_Travel'].notna()
df.loc[msk, 'Country_of_Travel'] = df.loc[msk, 'Country_of_Travel'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Country_of_Travel']= df.loc[msk,'Country_of_Travel'].apply(lambda x: x.lower())
df['Country_of_Travel'].nunique()

97

In [110]:
df[['Country_of_Travel']].value_counts(dropna=False)

Country_of_Travel
NaN                  14065246
united states          529710
germany                  2121
canada                   1496
ireland                  1127
                       ...
el salvador                 1
burkina faso                1
bolivia                     1
belize                      1
latvia                      1
Name: count, Length: 98, dtype: int64

In [111]:
# Verification after converting to lower case

df[['City_of_Travel','State_of_Travel','Country_of_Travel']].describe()

       City_of_Travel State_of_Travel Country_of_Travel
count          543986          529710            543987
unique           6596              56                97
top            dallas              TX     united states
freq            20680           68142            529710

### Payment indicaters

In [112]:
df['Record_ID']=df['Record_ID'].astype(object)

In [113]:
df[['Physician_Ownership_Indicator','Third_Party_Payment_Recipient_Indicator',
   'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value',
   'Charity_Indicator', 'Third_Party_Equals_Covered_Recipient_Indicator',
   'Contextual_Information','Delay_in_Publication_Indicator',
   'Record_ID', 'Dispute_Status_for_Publication','Related_Product_Indicator',
   'Covered_or_Noncovered_Indicator_1']].describe()

,Physician_Ownership_Indicator,Third_Party_Payment_Recipient_Indicator,Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value,Charity_Indicator,Third_Party_Equals_Covered_Recipient_Indicator,Contextual_Information,Delay_in_Publication_Indicator,Record_ID,Dispute_Status_for_Publication,Related_Product_Indicator,Covered_or_Noncovered_Indicator_1
count,12762944,14609233,97208,4124927,120996,865335,14609233,14609233,14609233,14609233,13782385
unique,2,3,13596,2,2,123635,1,14609233,2,2,2
top,No,No Third Party Payment,Hyatt Regency Jersey City,No,No,Informational Meal,No,966511191,No,Yes,Covered
freq,12754178,14488237,833,4124697,104814,415944,14609233,1,14609017,13782385,13380925

In [114]:
df[['Physician_Ownership_Indicator','Third_Party_Payment_Recipient_Indicator',
   'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value',
   'Charity_Indicator', 'Third_Party_Equals_Covered_Recipient_Indicator',
   'Contextual_Information','Delay_in_Publication_Indicator',
   'Record_ID', 'Dispute_Status_for_Publication','Related_Product_Indicator',
   'Covered_or_Noncovered_Indicator_1']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 11 columns):
 #   Column                                                             Dtype
---  ------                                                             -----
 0   Physician_Ownership_Indicator                                      object
 1   Third_Party_Payment_Recipient_Indicator                            object
 2   Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value  object
 3   Charity_Indicator                                                  object
 4   Third_Party_Equals_Covered_Recipient_Indicator                     object
 5   Contextual_Information                                             object
 6   Delay_in_Publication_Indicator                                     object
 7   Record_ID                                                          object
 8   Dispute_Status_for_Publication                                     object
 9   Related_Product_Indicator                                          object
 10  Covered_or_Noncovered_Indicator_1                                  object
dtypes: object(11)
memory usage: 1.2+ GB

In [115]:
df[['Physician_Ownership_Indicator']].value_counts(dropna=False)

Physician_Ownership_Indicator
No                               12754178
NaN                               1846289
Yes                                  8766
Name: count, dtype: int64

In [116]:
df[['Third_Party_Payment_Recipient_Indicator']].value_counts(dropna=False)

Third_Party_Payment_Recipient_Indicator
No Third Party Payment                     14488237
Entity                                        97282
Individual                                    23714
Name: count, dtype: int64

In [117]:
df[['Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value']].value_counts(dropna=False)

Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value
NaN                                                                  14512025
Hyatt Regency Jersey City                                                 833
Wink Productions                                                          659
American Express                                                          541
SWISSOTEL CHICAGO                                                         494
                                                                       ...
HACKENSACK UNIVERSITY MEDICAL CENTER FOUNDATION                             1
HADAR H WALDMAN MD INC                                                      1
HAI IL CORPORATION                                                          1
RUSHANG DILIPKUMAR PATEL                                                    1
Lifetime Eyecare Associates PA                                              1
Name: count, Length: 13597, dtype: int64

In [118]:
# Converting name of third party to lower case

msk = df['Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value'].notna()
df.loc[msk, 'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value'] = df.loc[msk, 'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value']= df.loc[msk,'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value'].apply(lambda x: x.lower())
df['Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value'].nunique()

12561

In [119]:
df[['Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value']].value_counts(dropna=False)

Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value
NaN                                                                  14512025
hyatt regency jersey city                                                 907
wink productions                                                          659
american express                                                          541
swissotel chicago                                                         494
                                                                       ...
retina vitreous associates medical group, inc                               1
apple spice catering                                                        1
retina consultants of tampa bay                                             1
jimmy johns - 0826                                                          1
little black raincloud inc                                                  1
Name: count, Length: 12562, dtype: int64

In [120]:
df[['Third_Party_Equals_Covered_Recipient_Indicator']].value_counts(dropna=False)

Third_Party_Equals_Covered_Recipient_Indicator
NaN                                               14488237
No                                                  104814
Yes                                                  16182
Name: count, dtype: int64

In [121]:
df[['Charity_Indicator']].value_counts(dropna=False)

Charity_Indicator
NaN                  10484306
No                    4124697
Yes                       230
Name: count, dtype: int64

In [122]:
df[['Contextual_Information']].value_counts(dropna=False)

Contextual_Information
NaN                               13743898
Informational Meal                  415944
3                                    65479
Educational Program                  43376
Sponsorship of Attendee (Meal)       30154
                                    ...
;2696187;Concur;12585862                 1
;2696186;Concur;10045010                 1
;2696185;Concur;10055379                 1
;2696184;Concur;12324041                 1
;2722434;Concur;11885153                 1
Name: count, Length: 123636, dtype: int64

In [123]:
# Converting contextual info to lower case

msk = df['Contextual_Information'].notna()
df.loc[msk, 'Contextual_Information'] = df.loc[msk, 'Contextual_Information'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Contextual_Information']= df.loc[msk,'Contextual_Information'].apply(lambda x: x.lower())
df['Contextual_Information'].nunique()

123499

In [124]:
# Verify after lower case conversion

df[['Contextual_Information']].value_counts(dropna=False)

Contextual_Information
NaN                               13743898
informational meal                  415944
3                                    65479
educational program                  43376
sponsorship of attendee (meal)       30154
                                    ...
;2696114;concur;20864595                 1
;2696113;concur;10002211                 1
;2696112;concur;11661654                 1
;2696111;concur;11596877                 1
;2722358;concur;10039484                 1
Name: count, Length: 123500, dtype: int64

In [125]:
df[['Delay_in_Publication_Indicator']].value_counts(dropna=False)

Delay_in_Publication_Indicator
No                                14609233
Name: count, dtype: int64

In [126]:
df[['Record_ID']].value_counts(dropna=False)

Record_ID
965827691     1
1033655957    1
1033655847    1
1033655855    1
1033655865    1
             ..
1006006637    1
1006006639    1
1006006641    1
1006006643    1
1060937045    1
Name: count, Length: 14609233, dtype: int64

In [127]:
df[['Dispute_Status_for_Publication']].value_counts(dropna=False)

Dispute_Status_for_Publication
No                                14609017
Yes                                    216
Name: count, dtype: int64

In [128]:
df[['Related_Product_Indicator']].value_counts(dropna=False)

Related_Product_Indicator
Yes                          13782385
No                             826848
Name: count, dtype: int64

In [129]:
df[['Covered_or_Noncovered_Indicator_1']].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_1
Covered                              13380925
NaN                                    826848
Non-Covered                            401460
Name: count, dtype: int64

In [130]:
#### revalidating after conversion to lower case

df[['Physician_Ownership_Indicator','Third_Party_Payment_Recipient_Indicator',
   'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value',
   'Charity_Indicator', 'Third_Party_Equals_Covered_Recipient_Indicator',
   'Contextual_Information','Delay_in_Publication_Indicator',
   'Record_ID', 'Dispute_Status_for_Publication','Related_Product_Indicator',
   'Covered_or_Noncovered_Indicator_1']].describe()

,Physician_Ownership_Indicator,Third_Party_Payment_Recipient_Indicator,Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value,Charity_Indicator,Third_Party_Equals_Covered_Recipient_Indicator,Contextual_Information,Delay_in_Publication_Indicator,Record_ID,Dispute_Status_for_Publication,Related_Product_Indicator,Covered_or_Noncovered_Indicator_1
count,12762944,14609233,97208,4124927,120996,865335,14609233,14609233,14609233,14609233,13782385
unique,2,3,12561,2,2,123499,1,14609233,2,2,2
top,No,No Third Party Payment,hyatt regency jersey city,No,No,informational meal,No,966511191,No,Yes,Covered
freq,12754178,14488237,907,4124697,104814,415944,14609233,1,14609017,13782385,13380925

### Product data

In [131]:
df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1',
   'Product_Category_or_Therapeutic_Area_1', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1',
   'Associated_Drug_or_Biological_NDC_1','Associated_Device_or_Medical_Supply_PDI_1',
   'Covered_or_Noncovered_Indicator_2','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2',
   'Product_Category_or_Therapeutic_Area_2','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
   'Associated_Drug_or_Biological_NDC_2','Associated_Device_or_Medical_Supply_PDI_2',
   'Covered_or_Noncovered_Indicator_3',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3']].describe()

,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1,Product_Category_or_Therapeutic_Area_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Associated_Drug_or_Biological_NDC_1,Associated_Device_or_Medical_Supply_PDI_1,Covered_or_Noncovered_Indicator_2,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2,Product_Category_or_Therapeutic_Area_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Associated_Drug_or_Biological_NDC_2,Associated_Device_or_Medical_Supply_PDI_2,Covered_or_Noncovered_Indicator_3,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3
count,13494105,13487507,13384945,10310594,2173915,2490504,2457281,2454185,2452134,2120141,278231,731633,721340
unique,4,2303,9201,1342,5184,2,4,696,2756,623,2153,2,4
top,Drug,NEUROSCIENCE,VRAYLAR,61874-115-31,00858637005017,Covered,Drug,Diabetes,Ozempic,0169-4132-12,00850291007154,Covered,Drug
freq,8213931,982536,487618,487618,101679,2442995,1650893,357453,140132,140132,34085,705539,411491

In [132]:
df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1',
   'Product_Category_or_Therapeutic_Area_1', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1',
   'Associated_Drug_or_Biological_NDC_1','Associated_Device_or_Medical_Supply_PDI_1',
   'Covered_or_Noncovered_Indicator_2','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2',
   'Product_Category_or_Therapeutic_Area_2','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
   'Associated_Drug_or_Biological_NDC_2','Associated_Device_or_Medical_Supply_PDI_2',
   'Covered_or_Noncovered_Indicator_3',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 13 columns):
 #   Column                                                     Dtype
---  ------                                                     -----
 0   Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1  object
 1   Product_Category_or_Therapeutic_Area_1                     object
 2   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1   object
 3   Associated_Drug_or_Biological_NDC_1                        object
 4   Associated_Device_or_Medical_Supply_PDI_1                  object
 5   Covered_or_Noncovered_Indicator_2                          object
 6   Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2  object
 7   Product_Category_or_Therapeutic_Area_2                     object
 8   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2   object
 9   Associated_Drug_or_Biological_NDC_2                        object
 10  Associated_Device_or_Medical_Supply_PDI_2                  object
 11  Covered_or_Noncovered_Indicator_3                          object
 12  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3  object
dtypes: object(13)
memory usage: 1.4+ GB

In [133]:
df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3']].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3
NaN                                                          13887893
Drug                                                           411491
Biological                                                     169288
Device                                                         138137
Medical Supply                                                   2424
Name: count, dtype: int64

In [134]:
df[['Covered_or_Noncovered_Indicator_3']].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_3
NaN                                  13877600
Covered                                705539
Non-Covered                             26094
Name: count, dtype: int64

In [135]:
df[['Associated_Drug_or_Biological_NDC_2']].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_2
NaN                                    12489092
0169-4132-12                             140132
0169-4303-13                             133616
0069-1085-30                             120894
72511-760-02                              79100
                                         ...
0006-4943-00                                  1
0186-4010-01                                  1
49230-530-10                                  1
64406-029-01                                  1
61314-318-01                                  1
Name: count, Length: 624, dtype: int64

In [136]:
df[['Associated_Device_or_Medical_Supply_PDI_2']].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_2
NaN                                          14331002
00850291007154                                  34085
00852454006301                                  14233
00810003380098                                  12768
05694310961011                                   9233
                                               ...
07613154598663                                      1
07613154379453                                      1
00817470000368                                      1
00855195006616                                      1
00817470001761                                      1
Name: count, Length: 2154, dtype: int64

In [137]:
df[['Product_Category_or_Therapeutic_Area_2']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_2
NaN                                       12155048
Diabetes                                    357453
INFECTIOUS DISEASES                         120894
VACCINES                                    117604
Cardiology                                   98667
                                            ...
Hygiene                                          1
VIROLOGY                                         1
MEDICAL                                          1
ERT FOR ALPHA-MANNOSIDOSIS                       1
CARDIOVASCULAR;METABOLIC DISEASE                 1
Name: count, Length: 697, dtype: int64

In [138]:
# Converting to lower case

msk = df['Product_Category_or_Therapeutic_Area_2'].notna()
df.loc[msk, 'Product_Category_or_Therapeutic_Area_2'] = df.loc[msk, 'Product_Category_or_Therapeutic_Area_2'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Product_Category_or_Therapeutic_Area_2']= df.loc[msk,'Product_Category_or_Therapeutic_Area_2'].apply(lambda x: x.lower())
df['Product_Category_or_Therapeutic_Area_2'].nunique()

636

In [139]:
df[['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2']].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2
NaN                                                         12157099
Ozempic                                                       140132
Rybelsus                                                      133616
PAXLOVID                                                      120894
Repatha                                                        79100
                                                              ...
Armada                                                             1
Anterolateral Distal Tibia Plate, Right, Short, 15-Hole            1
ADCIRCA                                                            1
NanoFUSE Bioactive DBM                                             1
1.5MM SYSTEM - CRANIOCURVE (TM) MESH                               1
Name: count, Length: 2757, dtype: int64

In [140]:
# Converting to lower case

msk = df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].notna()
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'] = df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2']= df.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].apply(lambda x: x.lower())
df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].nunique()

2721

In [141]:
df[['Covered_or_Noncovered_Indicator_2']].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_2
NaN                                  12118729
Covered                               2442995
Non-Covered                             47509
Name: count, dtype: int64

In [142]:
df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2']].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2
NaN                                                          12151952
Drug                                                          1650893
Biological                                                     471872
Device                                                         318107
Medical Supply                                                  16409
Name: count, dtype: int64

In [143]:
df[['Associated_Device_or_Medical_Supply_PDI_1']].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_1
NaN                                          12435318
00858637005017                                 101679
00357599819002                                  63034
00386270000385                                  50361
00643169781702                                  38605
                                               ...
00827002022744                                      1
00889024572911                                      1
00889981064832                                      1
00827002022553                                      1
10845854028803                                      1
Name: count, Length: 5185, dtype: int64

In [144]:
df[['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1',]].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1
NaN                                                         1224288
VRAYLAR                                                      487618
DUPIXENT                                                     240463
RINVOQ                                                       219176
MOUNJARO                                                     218941
                                                             ...
System SOMATOM Definition Edge                                    1
EZE-SIT VALVULOTOME                                               1
Promus ELITE                                                      1
9765F-055-RA                                                      1
Blank                                                             1
Name: count, Length: 9202, dtype: int64

In [145]:
# Converting to lower case

msk = df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].notna()
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'] = df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1']= df.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].apply(lambda x: x.lower())
df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].nunique()

8961

In [146]:
df[['Associated_Drug_or_Biological_NDC_1']].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_1
NaN                                    4298639
61874-115-31                            487618
0024-5914-01                            240463
0074-2306-30                            219176
0002-1506-80                            218941
                                        ...
0069-0238-01                                 1
57902-249-05                                 1
58284-100-14                                 1
72245-682-10                                 1
58809-650-08                                 1
Name: count, Length: 1343, dtype: int64

In [147]:
df[['Product_Category_or_Therapeutic_Area_1']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_1
NaN                                             1121726
NEUROSCIENCE                                     982536
Diabetes                                         674723
Immunology                                       581092
IMMUNOLOGY                                       567545
                                                 ...
RotaryRestorative InstrumentsHygiene / Perio          1
Hand Held Retractors                                  1
OIRTHOPEDICS                                          1
Arthroscope                                           1
CC - NEEDLES - INTRAOSSEOUS                           1
Name: count, Length: 2304, dtype: int64

In [148]:
# Converting to lower case

msk = df['Product_Category_or_Therapeutic_Area_1'].notna()
df.loc[msk, 'Product_Category_or_Therapeutic_Area_1'] = df.loc[msk, 'Product_Category_or_Therapeutic_Area_1'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Product_Category_or_Therapeutic_Area_1']= df.loc[msk,'Product_Category_or_Therapeutic_Area_1'].apply(lambda x: x.lower())
df['Product_Category_or_Therapeutic_Area_1'].nunique()

2139

In [149]:
df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1']].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1
Drug                                                         8213931
Device                                                       2970261
Biological                                                   2201313
NaN                                                          1115128
Medical Supply                                                108600
Name: count, dtype: int64

In [150]:
# Taking after conversion to lower case

df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1',
   'Product_Category_or_Therapeutic_Area_1', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1',
   'Associated_Drug_or_Biological_NDC_1','Associated_Device_or_Medical_Supply_PDI_1',
   'Covered_or_Noncovered_Indicator_2','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2',
   'Product_Category_or_Therapeutic_Area_2','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
   'Associated_Drug_or_Biological_NDC_2','Associated_Device_or_Medical_Supply_PDI_2',
   'Covered_or_Noncovered_Indicator_3',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3']].describe()

,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1,Product_Category_or_Therapeutic_Area_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Associated_Drug_or_Biological_NDC_1,Associated_Device_or_Medical_Supply_PDI_1,Covered_or_Noncovered_Indicator_2,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2,Product_Category_or_Therapeutic_Area_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Associated_Drug_or_Biological_NDC_2,Associated_Device_or_Medical_Supply_PDI_2,Covered_or_Noncovered_Indicator_3,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3
count,13494105,13487507,13384945,10310594,2173915,2490504,2457281,2454185,2452134,2120141,278231,731633,721340
unique,4,2139,8961,1342,5184,2,4,636,2721,623,2153,2,4
top,Drug,neuroscience,vraylar,61874-115-31,00858637005017,Covered,Drug,diabetes,ozempic,0169-4132-12,00850291007154,Covered,Drug
freq,8213931,1215815,487618,487618,101679,2442995,1650893,377225,140132,140132,34085,705539,411491

### More product categories

In [151]:
df[['Product_Category_or_Therapeutic_Area_3', 
    'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Associated_Drug_or_Biological_NDC_3','Associated_Device_or_Medical_Supply_PDI_3',
    'Covered_or_Noncovered_Indicator_4','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Product_Category_or_Therapeutic_Area_4','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Associated_Drug_or_Biological_NDC_4','Associated_Device_or_Medical_Supply_PDI_4',
    'Covered_or_Noncovered_Indicator_5',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5']].describe()

,Product_Category_or_Therapeutic_Area_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Associated_Drug_or_Biological_NDC_3,Associated_Device_or_Medical_Supply_PDI_3,Covered_or_Noncovered_Indicator_4,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Associated_Device_or_Medical_Supply_PDI_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5
count,720780,717607,575807,116087,293755,292828,292678,290232,201357,77297,135545,135473
unique,517,1942,423,1642,2,4,362,1115,221,1043,2,4
top,PAIN,NURTEC ODT,72618-3000-2,00852454006226,Covered,Drug,CNS,ARISTADA,65757-404-03,00852454006257,Covered,Drug
freq,123002,107479,107479,11880,289318,140197,83004,61717,61717,11880,134728,70230

In [152]:
df[['Product_Category_or_Therapeutic_Area_3', 
    'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Associated_Drug_or_Biological_NDC_3','Associated_Device_or_Medical_Supply_PDI_3',
    'Covered_or_Noncovered_Indicator_4','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Product_Category_or_Therapeutic_Area_4','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Associated_Drug_or_Biological_NDC_4','Associated_Device_or_Medical_Supply_PDI_4',
    'Covered_or_Noncovered_Indicator_5',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 12 columns):
 #   Column                                                     Dtype
---  ------                                                     -----
 0   Product_Category_or_Therapeutic_Area_3                     object
 1   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3   object
 2   Associated_Drug_or_Biological_NDC_3                        object
 3   Associated_Device_or_Medical_Supply_PDI_3                  object
 4   Covered_or_Noncovered_Indicator_4                          object
 5   Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4  object
 6   Product_Category_or_Therapeutic_Area_4                     object
 7   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4   object
 8   Associated_Drug_or_Biological_NDC_4                        object
 9   Associated_Device_or_Medical_Supply_PDI_4                  object
 10  Covered_or_Noncovered_Indicator_5                          object
 11  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5  object
dtypes: object(12)
memory usage: 1.3+ GB

In [153]:
df[['Product_Category_or_Therapeutic_Area_3']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_3
NaN                                       13888453
PAIN                                        123002
CNS                                          83014
VACCINES                                     77312
Immunology                                   34241
                                            ...
BOTOX THERAPEUTIC                                1
BONDING AGENT                                    1
Ortho[aedic                                      1
Knee & Hip - Implants - ACL Repair               1
Renal                                            1
Name: count, Length: 518, dtype: int64

In [154]:
# Converting to lower case

msk = df['Product_Category_or_Therapeutic_Area_3'].notna()
df.loc[msk, 'Product_Category_or_Therapeutic_Area_3'] = df.loc[msk, 'Product_Category_or_Therapeutic_Area_3'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Product_Category_or_Therapeutic_Area_3']= df.loc[msk,'Product_Category_or_Therapeutic_Area_3'].apply(lambda x: x.lower())
df['Product_Category_or_Therapeutic_Area_3'].nunique()

477

In [155]:
df[['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3']].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3
NaN                                                         13891626
NURTEC ODT                                                    107479
ARISTADA                                                       61717
SIMPONI ARIA                                                   33534
GARDASIL 9                                                     28045
                                                              ...
BIXCUT                                                             1
EVIS EXERA II ULTRASOUND GASTROVIDEOSCOPE                          1
ToggleLoc                                                          1
EVENITY                                                            1
Somatom Force                                                      1
Name: count, Length: 1943, dtype: int64

In [156]:
# Converting to lower case

msk = df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].notna()
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'] = df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3']= df.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].apply(lambda x: x.lower())
df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].nunique()

1931

In [157]:
df[['Associated_Drug_or_Biological_NDC_3']].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_3
NaN                                    14033426
72618-3000-2                             107479
65757-403-03                              61717
57894-350-01                              33534
0006-4119-03                              28045
                                         ...
0173-0881-01                                  1
0023-9652-01                                  1
50419-320-05                                  1
0023-5301-05                                  1
55513-073-30                                  1
Name: count, Length: 424, dtype: int64

In [158]:
df[['Associated_Device_or_Medical_Supply_PDI_3']].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_3
NaN                                          14493146
00852454006226                                  11880
05694310961158                                   9233
00818806020005                                   5299
00370858000096                                   4212
                                               ...
00846832072972                                      1
00888867344747                                      1
10888277720787                                      1
00888867325630                                      1
05050474604414                                      1
Name: count, Length: 1643, dtype: int64

In [159]:
df[['Covered_or_Noncovered_Indicator_4']].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_4
NaN                                  14315478
Covered                                289318
Non-Covered                              4437
Name: count, dtype: int64

In [160]:
df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4']].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4
NaN                                                          14316405
Drug                                                           140197
Device                                                          89345
Biological                                                      62243
Medical Supply                                                   1043
Name: count, dtype: int64

In [161]:
df[['Product_Category_or_Therapeutic_Area_4']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_4
NaN                                                              14316555
CNS                                                                 83004
Immunology                                                          33568
VACCINE                                                             18638
PAIN                                                                16031
                                                                   ...
Recon Shoulders or Extremity, Upper                                     1
Extremities & Trauma - Implants - Core Metal - BioSync Wedges           1
Probes                                                                  1
PSYCHIATRY                                                              1
ACCESSORIES                                                             1
Name: count, Length: 363, dtype: int64

In [162]:
# Converting to lower case

msk = df['Product_Category_or_Therapeutic_Area_4'].notna()
df.loc[msk, 'Product_Category_or_Therapeutic_Area_4'] = df.loc[msk, 'Product_Category_or_Therapeutic_Area_4'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Product_Category_or_Therapeutic_Area_4']= df.loc[msk,'Product_Category_or_Therapeutic_Area_4'].apply(lambda x: x.lower())
df['Product_Category_or_Therapeutic_Area_4'].nunique()

339

In [163]:
df[['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4']].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4
NaN                                                         14319001
ARISTADA                                                       61717
STELARA                                                        33537
LYBALVI                                                        21268
PAXLOVID                                                       15618
                                                              ...
HONIGUM                                                            1
HUBS                                                               1
TRACLEER                                                           1
HYBRID Guidewire                                                   1
3043-005                                                           1
Name: count, Length: 1116, dtype: int64

In [164]:
# Converting to lower case

msk = df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].notna()
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'] = df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4']= df.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].apply(lambda x: x.lower())
df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].nunique()

1112

In [165]:
df[['Product_Category_or_Therapeutic_Area_4']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_4
NaN                                       14316555
cns                                          83004
immunology                                   34377
pain                                         30264
vaccine                                      18638
                                            ...
ems                                              1
integrated pharmacy solutions                    1
imrpession material                              1
impression material                              1
accessories                                      1
Name: count, Length: 340, dtype: int64

In [166]:
# Converting to lower case

msk = df['Product_Category_or_Therapeutic_Area_4'].notna()
df.loc[msk, 'Product_Category_or_Therapeutic_Area_4'] = df.loc[msk, 'Product_Category_or_Therapeutic_Area_4'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Product_Category_or_Therapeutic_Area_4']= df.loc[msk,'Product_Category_or_Therapeutic_Area_4'].apply(lambda x: x.lower())
df['Product_Category_or_Therapeutic_Area_4'].nunique()

339

In [167]:
df[['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4']].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4
NaN                                                         14319001
aristada                                                       61717
stelara                                                        33537
lybalvi                                                        21268
paxlovid                                                       15618
                                                              ...
erisma-lp                                                          1
escitalopram                                                       1
rally                                                              1
evis eus endoscopic ultrasound center                              1
3043-005                                                           1
Name: count, Length: 1113, dtype: int64

In [168]:
df[['Associated_Drug_or_Biological_NDC_4']].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_4
NaN                                    14407876
65757-404-03                              61717
57894-060-03                              33537
65757-651-42                              21268
0069-1085-30                              15618
                                         ...
65649-003-30                                  1
0008-1123-12                                  1
66215-102-06                                  1
50242-070-01                                  1
50242-108-01                                  1
Name: count, Length: 222, dtype: int64

In [169]:
df[['Associated_Device_or_Medical_Supply_PDI_4']].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_4
NaN                                          14531936
00852454006257                                  11880
05694310961653                                   9233
00818806020029                                   5287
00847236012403                                   3202
                                               ...
10705034723112                                      1
00888867351134                                      1
00888867350762                                      1
00380652486545                                      1
00846832088447                                      1
Name: count, Length: 1044, dtype: int64

In [170]:
df[['Covered_or_Noncovered_Indicator_5']].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_5
NaN                                  14473688
Covered                                134728
Non-Covered                               817
Name: count, dtype: int64

In [171]:
df[['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5']].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5
NaN                                                          14473760
Drug                                                            70230
Device                                                          51911
Biological                                                      13141
Medical Supply                                                    191
Name: count, dtype: int64

In [172]:
# After converting to lower case
df[['Product_Category_or_Therapeutic_Area_3', 
    'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Associated_Drug_or_Biological_NDC_3','Associated_Device_or_Medical_Supply_PDI_3',
    'Covered_or_Noncovered_Indicator_4','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Product_Category_or_Therapeutic_Area_4','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Associated_Drug_or_Biological_NDC_4','Associated_Device_or_Medical_Supply_PDI_4',
    'Covered_or_Noncovered_Indicator_5',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5']].describe()

,Product_Category_or_Therapeutic_Area_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Associated_Drug_or_Biological_NDC_3,Associated_Device_or_Medical_Supply_PDI_3,Covered_or_Noncovered_Indicator_4,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Associated_Device_or_Medical_Supply_PDI_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5
count,720780,717607,575807,116087,293755,292828,292678,290232,201357,77297,135545,135473
unique,477,1931,423,1642,2,4,339,1112,221,1043,2,4
top,pain,nurtec odt,72618-3000-2,00852454006226,Covered,Drug,cns,aristada,65757-404-03,00852454006257,Covered,Drug
freq,137235,107479,107479,11880,289318,140197,83004,61717,61717,11880,134728,70230

### More product categories

In [173]:
df['Program_Year']=df['Program_Year'].astype(object)

In [174]:
df[['Product_Category_or_Therapeutic_Area_5','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5',
   'Associated_Drug_or_Biological_NDC_5','Associated_Device_or_Medical_Supply_PDI_5',
   'Program_Year','Payment_Publication_Date']].describe()

,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Associated_Device_or_Medical_Supply_PDI_5,Program_Year,Payment_Publication_Date
count,135413,135137,83317,44737,14609233,14609233
unique,286,655,112,674,1,1
top,CNS,LYBALVI,65757-652-42,05694310961134,2023,06/28/2024
freq,61717,56721,56721,9233,14609233,14609233

In [175]:
df[['Product_Category_or_Therapeutic_Area_5','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5',
   'Associated_Drug_or_Biological_NDC_5','Associated_Device_or_Medical_Supply_PDI_5',
   'Program_Year','Payment_Publication_Date']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 6 columns):
 #   Column                                                    Dtype
---  ------                                                    -----
 0   Product_Category_or_Therapeutic_Area_5                    object
 1   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5  object
 2   Associated_Drug_or_Biological_NDC_5                       object
 3   Associated_Device_or_Medical_Supply_PDI_5                 object
 4   Program_Year                                              object
 5   Payment_Publication_Date                                  object
dtypes: object(6)
memory usage: 668.8+ MB

In [176]:
df[['Product_Category_or_Therapeutic_Area_5']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_5
NaN                                       14473820
CNS                                          61717
VACCINE                                      11811
Implant Dentistry                            10940
Wound Care                                    9645
                                            ...
COMMUNICATIONS                                   1
Plastic Surgery                                  1
INFECTIOUS DISEASES                              1
Bone Health                                      1
ACCESSORIES                                      1
Name: count, Length: 287, dtype: int64

In [177]:
# Converting to lower case

msk = df['Product_Category_or_Therapeutic_Area_5'].notna()
df.loc[msk, 'Product_Category_or_Therapeutic_Area_5'] = df.loc[msk, 'Product_Category_or_Therapeutic_Area_5'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Product_Category_or_Therapeutic_Area_5']= df.loc[msk,'Product_Category_or_Therapeutic_Area_5'].apply(lambda x: x.lower())
df['Product_Category_or_Therapeutic_Area_5'].nunique()

275

In [178]:
df['Product_Category_or_Therapeutic_Area_5'].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_5
NaN                                                         14473820
cns                                                            61717
vaccine                                                        11811
implant dentistry                                              10940
ophthalmology                                                  10379
                                                              ...
biologics - consumables - cartilage repair - accessories           1
immunology                                                         1
guidewire                                                          1
recon shoulders or extremity, upper                                1
antibiotics                                                        1
Name: count, Length: 276, dtype: int64

In [179]:
df[['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5']].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
NaN                                                         14474096
LYBALVI                                                        56721
BIOHORIZONS                                                    11284
Kerecis Omega3 SurgiClose                                       9233
M-M-R II                                                        6748
                                                              ...
EVOLVE                                                             1
ERIC RETRIEVAL DEVICE                                              1
Dyna-Link TI                                                       1
Mobi-C                                                             1
MV3                                                                1
Name: count, Length: 656, dtype: int64

In [180]:
# Converting to lower case

msk = df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].notna()
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'] = df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].astype(str)
# Converting all names to lower first to verify. They should be 666 in count.
df.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5']= df.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].apply(lambda x: x.lower())
df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].nunique()

654

In [181]:
df['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
NaN                           14474096
lybalvi                          56721
biohorizons                      11284
kerecis omega3 surgiclose         9233
m-m-r ii                          6748
                                ...
hydropearl                           1
tubigrip                             1
adapt                                1
kolorz clearshield varnish           1
hall power                           1
Name: count, Length: 655, dtype: int64

In [182]:
df[['Associated_Drug_or_Biological_NDC_5']].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_5
NaN                                    14525916
65757-652-42                              56721
0006-4681-00                               6748
65757-500-03                               4996
72245-682-10                               4333
                                         ...
50242-070-01                                  1
0597-0140-30                                  1
58468-4663-1                                  1
58468-0225-1                                  1
58468-0220-1                                  1
Name: count, Length: 113, dtype: int64

In [183]:
df[['Associated_Device_or_Medical_Supply_PDI_5']].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_5
NaN                                          14564496
05694310961134                                   9233
00818806020678                                   5299
00847236000561                                   3355
05057056106502                                   2792
                                               ...
00888867190917                                      1
00846832092079                                      1
00888867190986                                      1
00888867202740                                      1
07332551975937                                      1
Name: count, Length: 675, dtype: int64

In [184]:
df[['Program_Year']].value_counts(dropna=False)

Program_Year
2023            14609233
Name: count, dtype: int64

In [185]:
df[['Payment_Publication_Date']].value_counts(dropna=False)

Payment_Publication_Date
06/28/2024                  14609233
Name: count, dtype: int64

In [186]:
# After convertin to lower case

df[['Product_Category_or_Therapeutic_Area_5','Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5',
   'Associated_Drug_or_Biological_NDC_5','Associated_Device_or_Medical_Supply_PDI_5',
   'Program_Year','Payment_Publication_Date']].describe()

,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Associated_Device_or_Medical_Supply_PDI_5,Program_Year,Payment_Publication_Date
count,135413,135137,83317,44737,14609233,14609233
unique,275,654,112,674,1,1
top,cns,lybalvi,65757-652-42,05694310961134,2023,06/28/2024
freq,61717,56721,56721,9233,14609233,14609233

In [187]:
# Dropping identified columns
df=df.drop(columns=['Change_Type','Teaching_Hospital_CCN','Teaching_Hospital_ID',
    'Covered_Recipient_NPI','Covered_Recipient_Middle_Name','Covered_Recipient_Name_Suffix',
    'Recipient_Primary_Business_Street_Address_Line1', 'Recipient_Primary_Business_Street_Address_Line2',
    'Recipient_City','Recipient_Zip_Code','Recipient_Province','Recipient_Postal_Code',
    'Covered_Recipient_Specialty_5','Covered_Recipient_Specialty_6', 'Covered_Recipient_License_State_code1',
    'Covered_Recipient_License_State_code2', 'Covered_Recipient_License_State_code3',
     'Covered_Recipient_License_State_code4','Covered_Recipient_License_State_code5','Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
])

In [188]:
# Saving the data
# df.to_csv('Master_general_data_clean_21stOct.csv')

## Feature engineering of gender column

In [189]:
df['Covered_Recipient_First_Name'].nunique()

76634

In [190]:
# Master data names
general_uniq_names=pd.Series(list(set(df['Covered_Recipient_First_Name'])))

In [201]:
name_list=general_uniq_names[general_uniq_names.notna()]
name_list

1             nureddin
2                idriz
3             bre'anne
4               sripad
5                   ye
             ...
76630          tao-nan
76631    frances grace
76632         zindadil
76633            blane
76634          axeline
Length: 76634, dtype: object

In [192]:
general_uniq_names[general_uniq_names.notna()].to_csv('general_uniq_names_21oct.csv')

# To run after clean name mappings are available.

In [193]:
# Adding gender to the name list

# df=pd.read_csv('Master_general_data_clean_21stOct.csv', low_memory=False)

In [194]:
names_gender_map=pd.read_csv('all_general_gender_3predictions.csv', index_col='Unnamed: 0')

names_gender_map.head()

,0,malcolm/REA_GenderIdentification_v1_Prediction,malcolm/REA_GenderIdentification_v1_Confidence,priyabrat/gender_Prediction,priyabrat/gender_Confidence,finetuned_llama3.1_Prediction
Unnamed: 0,,,,,,
1,keemlin,M,0.802583,M,0.778833,M
2,mathijs,M,0.969350,M,0.976669,M
3,mai-linh,F,0.988828,F,0.995088,F
4,narda,F,0.995995,F,0.997731,F
5,inamul,M,0.859444,M,0.869561,M

In [195]:
names_gender_map=names_gender_map.rename(columns={"0": "Covered_Recipient_First_Name"}, errors="raise")
names_gender_map.columns

Index(['Covered_Recipient_First_Name',
       'malcolm/REA_GenderIdentification_v1_Prediction',
       'malcolm/REA_GenderIdentification_v1_Confidence',
       'priyabrat/gender_Prediction', 'priyabrat/gender_Confidence',
       'finetuned_llama3.1_Prediction'],
      dtype='object')

In [196]:
names_gender_map['Covered_Recipient_First_Name'].nunique() # Verifying if number of names match

76633

In [198]:
name_list.nunique()

76634

In [203]:
difference= list (set(name_list)- set (names_gender_map['Covered_Recipient_First_Name'].unique()))
difference

['nan']

In [204]:
# Verifying if name count is same
df['Covered_Recipient_First_Name'].nunique()

76634

In [205]:
# Finding mode in gender for all the three predictions.
# Stastically improves the outcomes

names_gender_map['mode']= names_gender_map[['malcolm/REA_GenderIdentification_v1_Prediction','priyabrat/gender_Prediction','finetuned_llama3.1_Prediction']].mode(axis=1, numeric_only=False, dropna=True)

names_gender_map[['Covered_Recipient_First_Name','mode']]

           Covered_Recipient_First_Name mode
Unnamed: 0
1                               keemlin    M
2                               mathijs    M
3                              mai-linh    F
4                                 narda    F
5                                inamul    M
...                                 ...  ...
76629                        kelly-anne    F
76630                         rodriques    M
76631                             gizel    F
76632                           demytra    F
76633                              ayed    M

[76633 rows x 2 columns]

In [206]:
# Verifying few values
df['Covered_Recipient_First_Name'].head(7)

0        sy
1     james
2     peter
3       leo
4     karri
5      mark
6    joseph
Name: Covered_Recipient_First_Name, dtype: object

In [207]:
# Creating dictionary of names and gender mapping , using mode of all name predictions.
namesdict=names_gender_map.set_index('Covered_Recipient_First_Name')['mode'].to_dict()

In [216]:
namesdict.get('nan')

In [217]:
# df['Covered_Recipient_First_Name']

df['Covered_Recipient_gender'] = df['Covered_Recipient_First_Name'].map(namesdict)

In [218]:
# Verifying few values
df[['Covered_Recipient_First_Name','Covered_Recipient_gender']].head(7)

  Covered_Recipient_First_Name Covered_Recipient_gender
0                           sy                        M
1                        james                        M
2                        peter                        M
3                          leo                        M
4                        karri                        F
5                         mark                        M
6                       joseph                        M

In [219]:
df[df['Covered_Recipient_First_Name'].notna()][['Covered_Recipient_First_Name','Covered_Recipient_gender']].describe()

       Covered_Recipient_First_Name Covered_Recipient_gender
count                      14578551                 14578233
unique                        76634                        2
top                         michael                        M
freq                         251584                  7840388

In [220]:
# Verifying summary
df[['Covered_Recipient_First_Name','Covered_Recipient_gender']].describe()

       Covered_Recipient_First_Name Covered_Recipient_gender
count                      14578551                 14578233
unique                        76634                        2
top                         michael                        M
freq                         251584                  7840388

In [221]:
# Verifying few values
df[['Covered_Recipient_First_Name','Covered_Recipient_gender']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14609233 entries, 0 to 14609232
Data columns (total 2 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Covered_Recipient_First_Name  object
 1   Covered_Recipient_gender      object
dtypes: object(2)
memory usage: 222.9+ MB

In [222]:
# Verifying few values
df[['Covered_Recipient_gender']].value_counts()

Covered_Recipient_gender
M                           7840388
F                           6737845
Name: count, dtype: int64

In [ ]:
### Saving the master data

df.to_csv('Master_data_general_clean_26th_oct_with_gender.csv')

#### End ######

## Master file to import and use for all future analysis